'use client';

// /admin/hearst/engine — Engine Audit page
// Cartographie visuelle complète du moteur du simulateur :
//   1. Pipeline diagram (stages: state → bootstrap → solver → archetype → projection → fold → debt → waterfall)
//   2. Public Sources Library (PUBLIC_SOURCES_LIBRARY) — 48 datapoints, filtres operator/metric/geo/confidence
//   3. Deal Archetypes (DEAL_ARCHETYPES) — 8 cartes avec facteurs scaling
//   4. GPU Catalog (GPU_CATALOG) — 4 SKUs
//   5. Models × Clients (FIT_MATRIX) — heatmap fit
//   6. Constants — magic numbers exposés avec file:line + suggested_action
//   7. DB Tables — counts + freshness des 9 tables hearst_*
//   8. Health — warnings P0/P1/P2 issus de l'inventory
//   9. Live Trace — run une simulation + montre source_map résolu

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

import { PUBLIC_SOURCES_LIBRARY, OPERATORS, BUSINESS_MODELS, CLIENT_TYPES, SITE_READINESS } from '@/lib/hearst-constants';
import { DEAL_ARCHETYPES } from '@/lib/hearst-deal-structures';
import { GPU_CATALOG } from '@/lib/hearst-gpu-catalog';
import { FIT_MATRIX } from '@/lib/hearst-fit-matrix';
import SectionTabs from '@/components/hearst/SectionTabs';

const TABS = [
  { id: 'pipeline',  label: 'Pipeline' },
  { id: 'sources',   label: 'Sources' },
  { id: 'archetypes',label: 'Deal models' },
  { id: 'gpu',       label: 'GPU catalog' },
  { id: 'fit',       label: 'Fit matrix' },
  { id: 'constants', label: 'Constants' },
  { id: 'db',        label: 'DB tables' },
  { id: 'health',    label: 'Health' },
  { id: 'trace',     label: 'Live trace' },
];

const OPERATORS_BY_ID = Object.fromEntries(OPERATORS.map(o => [o.id, o]));

function fmtUsd(n) {
  if (n == null) return '—';
  if (Math.abs(n) >= 1e9) return `$${(n / 1e9).toFixed(2)}B`;
  if (Math.abs(n) >= 1e6) return `$${(n / 1e6).toFixed(2)}M`;
  if (Math.abs(n) >= 1e3) return `$${(n / 1e3).toFixed(1)}k`;
  return `$${n.toFixed(0)}`;
}
function fmtPct(n) {
  if (n == null) return '—';
  return `${(n * 100).toFixed(1)}%`;
}
function fmtDate(d) {
  if (!d) return '—';
  try { return new Date(d).toLocaleDateString(); } catch { return d; }
}

function exportJson(inventory) {
  if (!inventory) return;
  const blob = new Blob([JSON.stringify(inventory, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `engine-audit-${new Date().toISOString().slice(0, 10)}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportReport(inventory) {
  if (!inventory) return;
  const date = new Date().toISOString().slice(0, 10);
  const sources = inventory.catalogs?.public_sources || {};
  const magics = inventory.magic_numbers || [];
  const tables = inventory.db_tables || [];
  const warnings = inventory.health_warnings || [];
  const summary = inventory.health_summary || {};
  const p0 = summary.p0 ?? 0;
  const p1 = summary.p1 ?? 0;
  const p2 = summary.p2 ?? 0;

  // Sources by operator
  const byOperator = {};
  (PUBLIC_SOURCES_LIBRARY || []).forEach(s => {
    byOperator[s.operator_id] = (byOperator[s.operator_id] || 0) + 1;
  });

  const operatorRows = Object.entries(byOperator)
    .sort((a, b) => b[1] - a[1])
    .map(([op, count]) => `| ${OPERATORS_BY_ID[op]?.label || op} | ${count} |`)
    .join('\n');

  const magicRows = magics
    .map(m => `| ${m.label} | ${m.value} | ${m.file}:${m.line} | ${m.suggested_action || '—'} |`)
    .join('\n');

  const tableRows = tables
    .map(t => `| ${t.table} | ${t.error ? 'error' : t.count} | ${t.latest_change_at ? new Date(t.latest_change_at).toLocaleString() : '—'} |`)
    .join('\n');

  const p0Warnings = warnings.filter(w => w.severity === 'P0');
  const p1Warnings = warnings.filter(w => w.severity === 'P1');
  const p2Warnings = warnings.filter(w => w.severity === 'P2');

  const warnSection = (label, list) => {
    if (list.length === 0) return `## Warnings — ${label}\n\n_None_\n`;
    return `## Warnings — ${label}\n\n${list.map(w => `- [${w.label}] (${w.ref || '—'}) — ${w.detail || ''}`).join('\n')}\n`;
  };

  const md = `# Engine Audit Report — ${date}

## Summary
- Public sources: ${sources.total ?? PUBLIC_SOURCES_LIBRARY.length} (avg confidence ${sources.avg_confidence ?? '—'}/5)
- Deal archetypes: ${inventory.catalogs?.deal_archetypes?.total ?? DEAL_ARCHETYPES.length}
- Magic numbers: ${magics.length}
- DB tables OK: ${tables.filter(t => !t.error).length}/${tables.length}
- Warnings: ${p0} P0 · ${p1} P1 · ${p2} P2

## Sources by operator
| Operator | Count |
|---|---|
${operatorRows}

## Magic numbers
| Label | Value | File:Line | Suggested action |
|---|---|---|---|
${magicRows || '_None_'}

## DB tables
| Table | Rows | Latest change |
|---|---|---|
${tableRows || '_None_'}

${warnSection('P0', p0Warnings)}
${warnSection('P1', p1Warnings)}
${warnSection('P2', p2Warnings)}
---
Generated by /admin/hearst/engine
`;

  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `engine-audit-report-${date}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function EnginePage() {
  const [tab, setTab] = useState('pipeline');
  const [inventory, setInventory] = useState(null);
  const [inventoryError, setInventoryError] = useState(null);

  useEffect(() => {
    fetch('/api/admin/hearst/audit/inventory')
      .then(r => r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`)))
      .then(setInventory)
      .catch(e => setInventoryError(e.message));
  }, []);

  const totalWarnings = inventory
    ? ((inventory.health_summary?.p0 ?? 0) + (inventory.health_summary?.p1 ?? 0) + (inventory.health_summary?.p2 ?? 0))
    : 0;

  return (
    <div style={S.wrap}>
      <SectionTabs section="modeling" />
      <header style={S.header}>
        <div>
          <h1 style={S.title}>Engine Audit</h1>
          <div style={S.subtitle}>
            Inventaire complet du moteur du simulateur : sources, formules, magic numbers, état DB.
            {' '}<Link href="/admin/hearst/simulator" style={S.headerLink}>→ Open Simulator</Link>
          </div>
        </div>
        {inventory && (
          <div style={S.healthChips}>
            <Chip label={`${inventory.catalogs.public_sources.total} sources`} tone="ok" />
            <Chip label={`avg conf ${inventory.catalogs.public_sources.avg_confidence}/5`} tone="ok" />
            <button
              type="button"
              onClick={() => setTab('health')}
              style={{
                ...S.chip,
                cursor: 'pointer',
                background: (inventory.health_summary?.p0 ?? 0) > 0 ? 'var(--cp-accent-soft)' : 'var(--cp-surface-2)',
                color: (inventory.health_summary?.p0 ?? 0) > 0 ? 'var(--cp-accent)' : 'var(--cp-text-body)',
                border: '1px solid var(--cp-border)',
              }}
            >
              {totalWarnings} warnings
            </button>
            <Chip label={`${inventory.db_tables.filter(t => !t.error).length}/${inventory.db_tables.length} tables OK`}
                  tone={inventory.db_tables.every(t => !t.error) ? 'ok' : 'warn'} />
            <button
              type="button"
              onClick={() => exportJson(inventory)}
              style={S.exportBtn}
              title="Download raw inventory JSON"
            >
              Export JSON
            </button>
            <button
              type="button"
              onClick={() => exportReport(inventory)}
              style={S.exportBtn}
              title="Download audit report as Markdown"
            >
              Export Report
            </button>
          </div>
        )}
      </header>

      {inventoryError && (
        <div style={S.error}>Inventory error: {inventoryError}</div>
      )}

      <nav style={S.tabs} role="tablist">
        {TABS.map(t => (
          <button
            key={t.id}
            type="button"
            role="tab"
            aria-selected={tab === t.id}
            onClick={() => setTab(t.id)}
            style={{ ...S.tab, ...(tab === t.id ? S.tabActive : {}) }}
          >
            {t.label}
          </button>
        ))}
      </nav>

      {tab === 'pipeline'   && <PipelineTab inventory={inventory} />}
      {tab === 'sources'    && <SourcesTab />}
      {tab === 'archetypes' && <ArchetypesTab />}
      {tab === 'gpu'        && <GpuTab />}
      {tab === 'fit'        && <FitTab />}
      {tab === 'constants'  && <ConstantsTab inventory={inventory} />}
      {tab === 'db'         && <DbTab inventory={inventory} />}
      {tab === 'health'     && <HealthTab inventory={inventory} />}
      {tab === 'trace'      && <TraceTab />}
    </div>
  );
}

// ────────────────────────────────────────────────────────────
// HEALTH
// ────────────────────────────────────────────────────────────
function HealthTab({ inventory }) {
  if (!inventory) return <section style={S.section}><p style={S.p}>Loading…</p></section>;

  const warnings = inventory?.health_warnings || [];
  if (warnings.length === 0) {
    return (
      <section style={S.section}>
        <h2 style={S.h2}>Health checks</h2>
        <div style={S.healthAllOk}>All checks passed ✓</div>
      </section>
    );
  }

  const p0 = warnings.filter(w => w.severity === 'P0');
  const p1 = warnings.filter(w => w.severity === 'P1');
  const p2 = warnings.filter(w => w.severity === 'P2');

  return (
    <section style={S.section}>
      <h2 style={S.h2}>Health checks</h2>
      <p style={S.p}>
        Warnings issus de l'inventaire. P0 = bloquant, P1 = dégradé, P2 = cosmétique.
      </p>

      {p0.length > 0 && (
        <div style={S.healthGroup}>
          <div style={S.healthGroupHead}>
            <span style={{ ...S.healthBadge, background: 'var(--cp-accent-soft)', color: 'var(--cp-accent)', border: '1px solid var(--cp-accent)' }}>
              P0 · {p0.length}
            </span>
          </div>
          <div style={S.tableWrap}>
            <table style={S.table}>
              <thead>
                <tr>
                  <th style={S.th}>Label</th>
                  <th style={S.th}>Detail</th>
                  <th style={S.th}>Ref</th>
                  <th style={S.th}>Area</th>
                </tr>
              </thead>
              <tbody>
                {p0.map(w => (
                  <tr key={w.id}>
                    <td style={{ ...S.td, fontWeight: 700 }}>{w.label}</td>
                    <td style={{ ...S.td, color: 'var(--cp-text-muted)' }}>{w.detail}</td>
                    <td style={S.tdMono}><code>{w.ref}</code></td>
                    <td style={S.td}><span style={S.healthAreaChip}>{w.area}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {p1.length > 0 && (
        <div style={S.healthGroup}>
          <div style={S.healthGroupHead}>
            <span style={{ ...S.healthBadge, background: 'rgba(245,158,11,0.12)', color: '#d97706', border: '1px solid rgba(245,158,11,0.35)' }}>
              P1 · {p1.length}
            </span>
          </div>
          <div style={S.tableWrap}>
            <table style={S.table}>
              <thead>
                <tr>
                  <th style={S.th}>Label</th>
                  <th style={S.th}>Detail</th>
                  <th style={S.th}>Ref</th>
                  <th style={S.th}>Area</th>
                </tr>
              </thead>
              <tbody>
                {p1.map(w => (
                  <tr key={w.id}>
                    <td style={{ ...S.td, fontWeight: 700 }}>{w.label}</td>
                    <td style={{ ...S.td, color: 'var(--cp-text-muted)' }}>{w.detail}</td>
                    <td style={S.tdMono}><code>{w.ref}</code></td>
                    <td style={S.td}><span style={S.healthAreaChip}>{w.area}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {p2.length > 0 && (
        <div style={S.healthGroup}>
          <div style={S.healthGroupHead}>
            <span style={{ ...S.healthBadge, background: 'var(--cp-surface-2)', color: 'var(--cp-text-muted)', border: '1px solid var(--cp-border)' }}>
              P2 · {p2.length}
            </span>
          </div>
          <div style={S.tableWrap}>
            <table style={S.table}>
              <thead>
                <tr>
                  <th style={S.th}>Label</th>
                  <th style={S.th}>Detail</th>
                  <th style={S.th}>Ref</th>
                  <th style={S.th}>Area</th>
                </tr>
              </thead>
              <tbody>
                {p2.map(w => (
                  <tr key={w.id}>
                    <td style={{ ...S.td, fontWeight: 700 }}>{w.label}</td>
                    <td style={{ ...S.td, color: 'var(--cp-text-muted)' }}>{w.detail}</td>
                    <td style={S.tdMono}><code>{w.ref}</code></td>
                    <td style={S.td}><span style={S.healthAreaChip}>{w.area}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </section>
  );
}

// ────────────────────────────────────────────────────────────
// PIPELINE
// ────────────────────────────────────────────────────────────
function PipelineTab({ inventory }) {
  const stages = inventory?.pipeline_stages || [];
  const formulas = inventory?.critical_formulas || [];

  return (
    <section style={S.section}>
      <h2 style={S.h2}>Data flow</h2>
      <p style={S.p}>
        Chaque saisie du simulateur traverse 10 étages avant de produire la projection.
        Cliquer un étage révèle le fichier source et la fonction concernée.
      </p>

      <div style={S.pipelineGrid}>
        {stages.map((s, i) => (
          <PipelineNode key={s.id} stage={s} index={i + 1} last={i === stages.length - 1} />
        ))}
      </div>

      <h2 style={{ ...S.h2, marginTop: 32 }}>Critical formulas</h2>
      <div style={S.tableWrap}>
        <table style={S.table}>
          <thead>
            <tr>
              <th style={S.th}>Function</th>
              <th style={S.th}>Formula</th>
              <th style={S.th}>File</th>
              <th style={S.th}>Line</th>
            </tr>
          </thead>
          <tbody>
            {formulas.map(f => (
              <tr key={f.id}>
                <td style={S.tdMono}>{f.id}</td>
                <td style={S.td}>{f.formula}</td>
                <td style={S.tdMono}><code>{f.file}</code></td>
                <td style={S.tdMono}>{f.line}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function PipelineNode({ stage, index, last }) {
  const KIND_COLOR = {
    state:     'var(--cp-text-muted)',
    serialize: 'var(--cp-text-body)',
    data:      'var(--cp-accent)',
    math:      'var(--cp-text-primary)',
    rules:     'var(--cp-accent-strong, var(--cp-accent))',
  };
  return (
    <div style={S.pipelineRow}>
      <div style={S.pipelineNum}>{String(index).padStart(2, '0')}</div>
      <div style={{ ...S.pipelineNode, borderLeft: `3px solid ${KIND_COLOR[stage.kind] || 'var(--cp-border)'}` }}>
        <div style={S.pipelineNodeHead}>
          <span style={S.pipelineNodeLabel}>{stage.label}</span>
          <span style={S.pipelineKindChip}>{stage.kind}</span>
        </div>
        <div style={S.pipelineNodeFile}><code>{stage.file}</code></div>
        <div style={S.pipelineNodeDesc}>{stage.desc}</div>
      </div>
      {!last && <div style={S.pipelineArrow}>↓</div>}
    </div>
  );
}

// ────────────────────────────────────────────────────────────
// SOURCES (PUBLIC_SOURCES_LIBRARY)
// ────────────────────────────────────────────────────────────
function SourcesTab() {
  const [operatorFilter, setOperatorFilter] = useState('');
  const [confidenceFilter, setConfidenceFilter] = useState(0);
  const [geoFilter, setGeoFilter] = useState('');
  const [search, setSearch] = useState('');

  const operators = useMemo(() => {
    const set = new Set(PUBLIC_SOURCES_LIBRARY.map(s => s.operator_id));
    return Array.from(set).sort();
  }, []);

  const filtered = useMemo(() => {
    return PUBLIC_SOURCES_LIBRARY.filter(s => {
      if (operatorFilter && s.operator_id !== operatorFilter) return false;
      if (confidenceFilter && (s.confidence_score || 0) < confidenceFilter) return false;
      if (geoFilter) {
        const g = (s.geography || '').toLowerCase();
        if (geoFilter === 'qatar' && !g.includes('qatar')) return false;
        if (geoFilter === 'mena' && !(g.includes('mena') || g.includes('gulf'))) return false;
        if (geoFilter === 'global' && (g.includes('qatar') || g.includes('mena'))) return false;
      }
      if (search) {
        const q = search.toLowerCase();
        const blob = `${s.metric_name} ${s.metric_id} ${s.source_name} ${s.operator_id}`.toLowerCase();
        if (!blob.includes(q)) return false;
      }
      return true;
    });
  }, [operatorFilter, confidenceFilter, geoFilter, search]);

  return (
    <section style={S.section}>
      <h2 style={S.h2}>Public Sources Library</h2>
      <p style={S.p}>
        {PUBLIC_SOURCES_LIBRARY.length} datapoints externes utilisés par <code>bootstrapScenarioFromSources</code>{' '}
        pour pré-remplir les scénarios. Médiane robuste par <code>metric_id</code>, filtre Qatar→MENA→Global en cascade.
      </p>

      <div style={S.filterRow}>
        <input
          type="search"
          placeholder="Search metric, source, operator…"
          value={search}
          onChange={e => setSearch(e.target.value)}
          style={S.searchInput}
        />
        <select value={operatorFilter} onChange={e => setOperatorFilter(e.target.value)} style={S.select}>
          <option value="">All operators</option>
          {operators.map(op => <option key={op} value={op}>{OPERATORS_BY_ID[op]?.label || op}</option>)}
        </select>
        <select value={geoFilter} onChange={e => setGeoFilter(e.target.value)} style={S.select}>
          <option value="">All regions</option>
          <option value="qatar">Qatar</option>
          <option value="mena">MENA/Gulf</option>
          <option value="global">Global only</option>
        </select>
        <select value={confidenceFilter} onChange={e => setConfidenceFilter(Number(e.target.value))} style={S.select}>
          <option value={0}>Any confidence</option>
          <option value={3}>≥ 3</option>
          <option value={4}>≥ 4</option>
          <option value={5}>= 5 (high)</option>
        </select>
        <span style={S.countPill}>{filtered.length} / {PUBLIC_SOURCES_LIBRARY.length}</span>
      </div>

      <div style={S.tableWrap}>
        <table style={S.table}>
          <thead>
            <tr>
              <th style={S.th}>Operator</th>
              <th style={S.th}>Metric</th>
              <th style={S.thNum}>Value</th>
              <th style={S.th}>Unit</th>
              <th style={S.th}>Geo</th>
              <th style={S.thNum}>Conf</th>
              <th style={S.th}>Published</th>
              <th style={S.th}>Source</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map(s => (
              <tr key={s.id}>
                <td style={S.td}>{OPERATORS_BY_ID[s.operator_id]?.label || s.operator_id}</td>
                <td style={S.tdMono}>{s.metric_name}<div style={S.tinyMono}>{s.metric_id}</div></td>
                <td style={S.tdNum}>{typeof s.value === 'number' && s.value < 1 ? s.value.toFixed(3) : (s.value?.toLocaleString?.() ?? '—')}</td>
                <td style={S.td}>{s.unit}</td>
                <td style={S.td}>{s.geography}</td>
                <td style={S.tdNum}>
                  <ConfidenceDot score={s.confidence_score} />
                </td>
                <td style={S.td}>{fmtDate(s.date_published)}</td>
                <td style={S.td}>
                  {s.url ? <a href={s.url} target="_blank" rel="noreferrer" style={S.link}>{s.source_name}</a> : s.source_name}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

function ConfidenceDot({ score }) {
  const s = score ?? 0;
  const dots = [1, 2, 3, 4, 5].map(i => (
    <span key={i} style={{ ...S.confDot, background: i <= s ? 'var(--cp-text-primary)' : 'var(--cp-border)' }} />
  ));
  return <span style={S.confDots}>{dots}</span>;
}

// ────────────────────────────────────────────────────────────
// ARCHETYPES
// ────────────────────────────────────────────────────────────
function ArchetypesTab() {
  return (
    <section style={S.section}>
      <h2 style={S.h2}>Deal Archetypes ({DEAL_ARCHETYPES.length})</h2>
      <p style={S.p}>
        Chaque archetype scale les inputs du scénario (capex, revenue, opex) avant projection.
        Source : <code>lib/hearst-deal-structures.js#DEAL_ARCHETYPES</code>.
      </p>
      <div style={S.archGrid}>
        {DEAL_ARCHETYPES.map(a => <ArchetypeCard key={a.id} arch={a} />)}
      </div>
    </section>
  );
}

function ArchetypeCard({ arch }) {
  return (
    <div style={S.archCard}>
      <header style={S.archCardHead}>
        <div>
          <div style={S.archCode}>{arch.code} · {arch.id}</div>
          <div style={S.archLabel}>{arch.label}</div>
        </div>
        {arch.recommended && <span style={S.recommendedChip}>RECOMMENDED</span>}
      </header>
      <div style={S.archShort}>{arch.short}</div>

      <div style={S.archFacts}>
        <Fact label="Revenue factor"  value={fmtPct(arch.revenue_factor)} />
        <Fact label="Opex factor"     value={fmtPct(arch.opex_factor)} />
        <Fact label="Operator fee"    value={arch.operator_fee_pct != null ? `${arch.operator_fee_pct}%` : '—'} />
        <Fact label="Debt Δ (bps)"    value={arch.debt_rate_delta_bps != null ? (arch.debt_rate_delta_bps > 0 ? `+${arch.debt_rate_delta_bps}` : `${arch.debt_rate_delta_bps}`) : '—'} />
        <Fact label="Compute as"      value={arch.compute_as || 'recurring_revenue'} />
        {arch.equity_share != null && <Fact label="Equity share" value={fmtPct(arch.equity_share)} />}
      </div>

      {arch.capex_component_factor && (
        <div style={S.archFactorTable}>
          <div style={S.archFactorTitle}>CAPEX coverage (Hearst-side)</div>
          {Object.entries(arch.capex_component_factor).map(([k, v]) => (
            <div key={k} style={S.archFactorRow}>
              <span style={S.archFactorKey}>{k.replace('capex_', '').replace('_per_mw', '')}</span>
              <span style={S.archFactorBar}>
                <span style={{ ...S.archFactorBarFill, width: `${Math.max(0, Math.min(100, v * 100))}%` }} />
              </span>
              <span style={S.archFactorVal}>{fmtPct(v)}</span>
            </div>
          ))}
        </div>
      )}

      <div style={S.archScores}>
        {arch.scores && Object.entries(arch.scores).map(([k, v]) => (
          <div key={k} style={S.archScore}>
            <div style={S.archScoreLabel}>{k}</div>
            <div style={S.archScoreVal}>{v}/5</div>
          </div>
        ))}
      </div>

      {arch.real_comp && (
        <div style={S.archComp}>
          <span style={S.archCompLabel}>Real comparable</span>
          <span style={S.archCompText}>{arch.real_comp}</span>
        </div>
      )}
    </div>
  );
}

function Fact({ label, value }) {
  return (
    <div style={S.fact}>
      <div style={S.factLabel}>{label}</div>
      <div style={S.factValue}>{value}</div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────
// GPU CATALOG
// ────────────────────────────────────────────────────────────
function GpuTab() {
  return (
    <section style={S.section}>
      <h2 style={S.h2}>GPU Catalog ({GPU_CATALOG.length})</h2>
      <p style={S.p}>
        Source : <code>lib/hearst-gpu-catalog.js#GPU_CATALOG</code>.
        Magic numbers appliqués : host overhead <code>×1.15</code>, hardware markup <code>×1.15</code>.
      </p>
      <div style={S.gpuGrid}>
        {GPU_CATALOG.map(g => (
          <div key={g.id} style={S.gpuCard}>
            <header style={S.gpuHead}>
              <div style={S.gpuVendor}>{g.vendor}</div>
              <div style={S.gpuSku}>{g.sku}</div>
            </header>
            <div style={S.gpuFacts}>
              <Fact label="TDP" value={g.rack_scale ? `${(g.tdp_w / 1000).toFixed(0)} kW/rack` : `${g.tdp_w}W`} />
              <Fact label="MSRP" value={fmtUsd(g.msrp_usd)} />
              <Fact label="Density/rack" value={g.density_per_rack} />
              <Fact label="HBM" value={`${g.hbm_gb} GB`} />
              <Fact label="FP16" value={`${(g.perf_tflops_fp16 / 1000).toFixed(1)} PF`} />
              <Fact label="Use case" value={g.use_case} />
              <Fact label="Available" value={g.available_from} />
              <Fact label="Rack-scale" value={g.rack_scale ? 'Yes' : 'No'} />
            </div>
            {g.notes && <div style={S.gpuNotes}>{g.notes}</div>}
            <a href={g.reference_url} target="_blank" rel="noreferrer" style={S.link}>Reference →</a>
          </div>
        ))}
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────
// FIT MATRIX
// ────────────────────────────────────────────────────────────
function FitTab() {
  return (
    <section style={S.section}>
      <h2 style={S.h2}>Business model × Client type ({Object.keys(FIT_MATRIX).length} cells)</h2>
      <p style={S.p}>
        Source : <code>lib/hearst-fit-matrix.js#FIT_MATRIX</code>. Score 1–5, prix typique, marge EBITDA.
      </p>
      <div style={S.fitWrap}>
        <table style={{ ...S.table, fontSize: 11 }}>
          <thead>
            <tr>
              <th style={S.th}>Business model</th>
              {CLIENT_TYPES.map(c => (
                <th key={c.id} style={S.th}>{c.id.replace('_', ' ')}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {BUSINESS_MODELS.map(m => (
              <tr key={m.id}>
                <td style={{ ...S.td, fontWeight: 700 }}>{m.label}</td>
                {CLIENT_TYPES.map(c => {
                  const cell = FIT_MATRIX[`${m.id}::${c.id}`];
                  if (!cell) return <td key={c.id} style={S.tdMuted}>—</td>;
                  const intensity = cell.fit / 5;
                  return (
                    <td key={c.id} style={{
                      ...S.td,
                      background: `color-mix(in srgb, var(--cp-accent) ${intensity * 35}%, transparent)`,
                      textAlign: 'center',
                      lineHeight: 1.2,
                    }}>
                      <div style={{ fontWeight: 700, fontSize: 12 }}>{cell.fit}/5</div>
                      <div style={{ fontSize: 10, color: 'var(--cp-text-muted)' }}>
                        {typeof cell.pricing === 'number' ? `$${cell.pricing}` : cell.pricing}
                      </div>
                      <div style={{ fontSize: 10, color: 'var(--cp-text-muted)' }}>{fmtPct(cell.margin)}</div>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────
// CONSTANTS / MAGIC NUMBERS
// ────────────────────────────────────────────────────────────
function ConstantsTab({ inventory }) {
  const magics = inventory?.magic_numbers || [];
  return (
    <section style={S.section}>
      <h2 style={S.h2}>Magic numbers ({magics.length})</h2>
      <p style={S.p}>
        Valeurs hardcodées dans le moteur de calcul. À paramétrer scénario-par-scénario à terme.
      </p>
      <div style={S.tableWrap}>
        <table style={S.table}>
          <thead>
            <tr>
              <th style={S.th}>Constant</th>
              <th style={S.thNum}>Value</th>
              <th style={S.th}>Unit</th>
              <th style={S.th}>File</th>
              <th style={S.th}>Why</th>
              <th style={S.th}>Suggested action</th>
            </tr>
          </thead>
          <tbody>
            {magics.map(m => (
              <tr key={m.id}>
                <td style={S.tdMono}>{m.label}</td>
                <td style={S.tdNum}>{String(m.value)}</td>
                <td style={S.td}>{m.unit}</td>
                <td style={S.tdMono}>{m.file}:{m.line}</td>
                <td style={S.td}>{m.why}</td>
                <td style={{ ...S.td, color: 'var(--cp-accent)' }}>{m.suggested_action}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 style={{ ...S.h2, marginTop: 32 }}>Site readiness states ({Object.keys(SITE_READINESS).length})</h2>
      <div style={S.tableWrap}>
        <table style={S.table}>
          <thead>
            <tr>
              <th style={S.th}>State</th>
              <th style={S.thNum}>COD offset (mo)</th>
              <th style={S.thNum}>Risk</th>
              <th style={S.thNum}>Contingency %</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(SITE_READINESS).map(([k, v]) => (
              <tr key={k}>
                <td style={S.tdMono}>{k}</td>
                <td style={S.tdNum}>{v.cod_offset_months ?? v.cod_offset ?? '—'}</td>
                <td style={S.tdNum}>{v.risk ?? '—'}</td>
                <td style={S.tdNum}>{v.contingency_pct ?? '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────
// DB TABLES
// ────────────────────────────────────────────────────────────
function DbTab({ inventory }) {
  const tables = inventory?.db_tables || [];
  const env = inventory?.env || {};
  return (
    <section style={S.section}>
      <h2 style={S.h2}>Supabase tables ({tables.length})</h2>
      <p style={S.p}>Read-only counts + freshness. Aucune mutation faite par cette page.</p>
      <div style={S.tableWrap}>
        <table style={S.table}>
          <thead>
            <tr>
              <th style={S.th}>Table</th>
              <th style={S.thNum}>Rows</th>
              <th style={S.th}>Latest change</th>
              <th style={S.th}>Status</th>
            </tr>
          </thead>
          <tbody>
            {tables.map(t => (
              <tr key={t.table}>
                <td style={S.tdMono}>{t.table}</td>
                <td style={S.tdNum}>{t.error ? '—' : t.count}</td>
                <td style={S.td}>{t.latest_change_at ? new Date(t.latest_change_at).toLocaleString() : '—'}</td>
                <td style={S.td}>
                  {t.error ? <span style={S.errChip}>{t.error}</span> : <span style={S.okChip}>OK</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 style={{ ...S.h2, marginTop: 32 }}>Environment</h2>
      <div style={S.envGrid}>
        {Object.entries(env).map(([k, v]) => (
          <div key={k} style={S.envCell}>
            <div style={S.envKey}>{k}</div>
            <div style={S.envVal}>{typeof v === 'boolean' ? (v ? '✓ set' : '✗ missing') : String(v)}</div>
          </div>
        ))}
      </div>
    </section>
  );
}

// ────────────────────────────────────────────────────────────
// LIVE TRACE
// ────────────────────────────────────────────────────────────
function TraceTab() {
  const [mw, setMw] = useState(50);
  const [archetypeId, setArchetypeId] = useState('powered_shell');
  const [businessModelId, setBusinessModelId] = useState('hyperscale_lease');
  const [geography, setGeography] = useState('qatar');
  const [trace, setTrace] = useState(null);
  const [tracing, setTracing] = useState(false);
  const [traceError, setTraceError] = useState(null);

  async function runTrace() {
    setTracing(true);
    setTraceError(null);
    try {
      const r = await fetch('/api/admin/hearst/simulate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          input_mode: 'mw_first',
          input_value: { total_mw: mw },
          archetype_id: archetypeId,
          business_model_id: businessModelId,
          geography,
        }),
      });
      if (!r.ok) {
        const body = await r.json().catch(() => ({}));
        throw new Error(body.error || `HTTP ${r.status}`);
      }
      const data = await r.json();
      setTrace(data);
    } catch (e) {
      setTraceError(e.message);
    } finally {
      setTracing(false);
    }
  }

  const sourceMapEntries = useMemo(() => {
    if (!trace?.source_map) return [];
    const byId = Object.fromEntries(PUBLIC_SOURCES_LIBRARY.map(s => [s.id, s]));
    return Object.entries(trace.source_map).map(([field, sourceId]) => ({
      field,
      source: byId[sourceId],
      sourceId,
    }));
  }, [trace]);

  return (
    <section style={S.section}>
      <h2 style={S.h2}>Live trace</h2>
      <p style={S.p}>
        Lance une simulation et trace exactement quelles sources publiques ont été utilisées pour chaque champ du scénario.
      </p>

      <div style={S.traceControls}>
        <div style={S.traceField}>
          <label style={S.traceLabel}>MW</label>
          <input type="number" value={mw} min={5} max={1000} onChange={e => setMw(Number(e.target.value))} style={S.traceInput} />
        </div>
        <div style={S.traceField}>
          <label style={S.traceLabel}>Archetype</label>
          <select value={archetypeId} onChange={e => setArchetypeId(e.target.value)} style={S.select}>
            {DEAL_ARCHETYPES.map(a => <option key={a.id} value={a.id}>{a.label}</option>)}
          </select>
        </div>
        <div style={S.traceField}>
          <label style={S.traceLabel}>Business model</label>
          <select value={businessModelId} onChange={e => setBusinessModelId(e.target.value)} style={S.select}>
            {BUSINESS_MODELS.map(m => <option key={m.id} value={m.id}>{m.label}</option>)}
          </select>
        </div>
        <div style={S.traceField}>
          <label style={S.traceLabel}>Geography</label>
          <select value={geography} onChange={e => setGeography(e.target.value)} style={S.select}>
            <option value="qatar">Qatar</option>
            <option value="mena">MENA</option>
            <option value="global">Global</option>
          </select>
        </div>
        <button type="button" onClick={runTrace} disabled={tracing} style={S.traceBtn}>
          {tracing ? 'Running…' : 'Run trace'}
        </button>
      </div>

      {traceError && <div style={S.error}>{traceError}</div>}

      {trace && (
        <>
          <div style={S.traceKpis}>
            <Kpi label="Confidence" value={`${trace.confidence_score}%`} hint="% des critical metrics avec source" />
            <Kpi label="Total CAPEX" value={fmtUsd(trace.projection?.total_capex)} />
            <Kpi label="Stabilized revenue" value={fmtUsd(trace.projection?.stabilized_revenue)} />
            <Kpi label="Stabilized EBITDA" value={fmtUsd(trace.projection?.stabilized_ebitda)} />
            <Kpi label="IRR" value={fmtPct(trace.projection?.irr)} />
            <Kpi label="MOIC" value={trace.projection?.moic ? `${trace.projection.moic.toFixed(2)}×` : '—'} />
            <Kpi label="Payback" value={trace.projection?.payback_years ? `${trace.projection.payback_years} yr` : '—'} />
            <Kpi label="DSCR" value={trace.projection?.dscr_stabilized ? `${trace.projection.dscr_stabilized.toFixed(2)}×` : '—'} />
          </div>

          <h3 style={S.h3}>Source map ({sourceMapEntries.length} fields resolved)</h3>
          <div style={S.tableWrap}>
            <table style={S.table}>
              <thead>
                <tr>
                  <th style={S.th}>Scenario field</th>
                  <th style={S.thNum}>Value</th>
                  <th style={S.th}>Source ID</th>
                  <th style={S.th}>Source name</th>
                  <th style={S.thNum}>Confidence</th>
                </tr>
              </thead>
              <tbody>
                {sourceMapEntries.map(({ field, source, sourceId }) => (
                  <tr key={field}>
                    <td style={S.tdMono}>{field}</td>
                    <td style={S.tdNum}>{trace.scenario?.[field] != null ? trace.scenario[field].toLocaleString?.() ?? trace.scenario[field] : '—'}</td>
                    <td style={S.tdMono}>{sourceId}</td>
                    <td style={S.td}>
                      {source ? (
                        source.url
                          ? <a href={source.url} target="_blank" rel="noreferrer" style={S.link}>{source.source_name}</a>
                          : source.source_name
                      ) : <span style={S.errChip}>unknown</span>}
                    </td>
                    <td style={S.tdNum}>{source ? <ConfidenceDot score={source.confidence_score} /> : '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {trace.solver && (
            <>
              <h3 style={S.h3}>Solver diagnostic</h3>
              <pre style={S.pre}>{JSON.stringify(trace.solver, null, 2)}</pre>
            </>
          )}

          <details style={S.details}>
            <summary style={S.summary}>Full resolved scenario ({Object.keys(trace.scenario || {}).length} fields)</summary>
            <pre style={S.pre}>{JSON.stringify(trace.scenario, null, 2)}</pre>
          </details>

          <details style={S.details}>
            <summary style={S.summary}>10-year projection</summary>
            <pre style={S.pre}>{JSON.stringify(trace.projection?.years || [], null, 2)}</pre>
          </details>
        </>
      )}
    </section>
  );
}

// ────────────────────────────────────────────────────────────
// Atoms
// ────────────────────────────────────────────────────────────
function Chip({ label, tone }) {
  const bg = tone === 'ok' ? 'var(--cp-surface-2)' : tone === 'warn' ? 'var(--cp-accent-soft)' : 'var(--cp-surface-2)';
  const fg = tone === 'warn' ? 'var(--cp-accent)' : 'var(--cp-text-body)';
  return <span style={{ ...S.chip, background: bg, color: fg }}>{label}</span>;
}
function Kpi({ label, value, hint }) {
  return (
    <div style={S.kpi}>
      <div style={S.kpiLabel}>{label}</div>
      <div style={S.kpiValue}>{value ?? '—'}</div>
      {hint && <div style={S.kpiHint}>{hint}</div>}
    </div>
  );
}

// ────────────────────────────────────────────────────────────
// Design tokens — local (cohérent avec /admin/hearst/simulator)
// ────────────────────────────────────────────────────────────
const S = {
  wrap: {
    display: 'flex', flexDirection: 'column', gap: 24,
    maxWidth: 1280, margin: '0 auto', padding: '32px 32px 96px',
  },
  header: {
    display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end',
    gap: 16, paddingBottom: 16, borderBottom: '1px solid var(--cp-border)',
    flexWrap: 'wrap',
  },
  title: { fontSize: 28, lineHeight: '36px', fontWeight: 800, letterSpacing: -0.4, color: 'var(--cp-text-primary)', margin: 0 },
  subtitle: { fontSize: 13, lineHeight: '20px', color: 'var(--cp-text-muted)', marginTop: 4 },
  headerLink: { color: 'var(--cp-accent)', textDecoration: 'none', marginLeft: 8 },
  healthChips: { display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  chip: {
    fontSize: 11, fontWeight: 700, padding: '6px 12px',
    border: '1px solid var(--cp-border)', borderRadius: 999,
    letterSpacing: 0.3, whiteSpace: 'nowrap',
  },

  tabs: {
    display: 'flex', gap: 4, padding: 4,
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    borderRadius: 999, alignSelf: 'flex-start', flexWrap: 'wrap',
  },
  tab: {
    fontSize: 12, height: 32, padding: '0 16px',
    background: 'transparent', color: 'var(--cp-text-muted)',
    border: 'none', borderRadius: 999, cursor: 'pointer',
    fontWeight: 700, letterSpacing: 0.3, transition: 'all 0.15s ease',
  },
  tabActive: { background: 'var(--cp-accent-maroon, var(--cp-accent))', color: 'var(--cp-text-strong)' },

  section: { display: 'flex', flexDirection: 'column', gap: 16 },
  h2: { fontSize: 18, fontWeight: 700, color: 'var(--cp-text-primary)', margin: 0 },
  h3: { fontSize: 14, fontWeight: 700, color: 'var(--cp-text-primary)', margin: '16px 0 8px' },
  p: { fontSize: 13, color: 'var(--cp-text-muted)', lineHeight: 1.5, margin: 0 },

  error: {
    padding: '12px 16px', background: 'var(--cp-accent-soft)',
    color: 'var(--cp-text-strong)', border: '1px solid var(--cp-accent)',
    borderRadius: 10, fontSize: 12, fontWeight: 600,
  },

  // Pipeline
  pipelineGrid: { display: 'flex', flexDirection: 'column', gap: 8, marginTop: 8 },
  pipelineRow: { display: 'flex', alignItems: 'flex-start', gap: 12 },
  pipelineNum: {
    fontSize: 11, fontWeight: 700, color: 'var(--cp-text-muted)',
    width: 28, paddingTop: 14, textAlign: 'right',
    fontFamily: 'ui-monospace, monospace',
  },
  pipelineNode: {
    flex: 1, padding: '12px 16px',
    background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)',
    borderRadius: 10,
  },
  pipelineNodeHead: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 },
  pipelineNodeLabel: { fontSize: 13, fontWeight: 700, color: 'var(--cp-text-primary)' },
  pipelineKindChip: {
    fontSize: 9, fontWeight: 700, padding: '2px 8px',
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    color: 'var(--cp-text-muted)', borderRadius: 999,
    textTransform: 'uppercase', letterSpacing: 0.5,
  },
  pipelineNodeFile: { fontSize: 11, fontFamily: 'ui-monospace, monospace', color: 'var(--cp-text-muted)', marginBottom: 4 },
  pipelineNodeDesc: { fontSize: 12, color: 'var(--cp-text-body)' },
  pipelineArrow: { color: 'var(--cp-text-muted)', fontSize: 16, marginLeft: 28, lineHeight: '24px' },

  // Filter row
  filterRow: { display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' },
  searchInput: {
    flex: '1 1 240px', height: 36, padding: '0 12px',
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    borderRadius: 8, color: 'var(--cp-text-primary)', fontSize: 12,
  },
  select: {
    height: 36, padding: '0 12px',
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    borderRadius: 8, color: 'var(--cp-text-primary)', fontSize: 12,
  },
  countPill: {
    fontSize: 11, fontWeight: 700, padding: '6px 12px',
    background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)',
    borderRadius: 999, color: 'var(--cp-text-muted)',
  },

  // Tables
  tableWrap: {
    border: '1px solid var(--cp-border)', borderRadius: 10,
    overflow: 'auto', maxHeight: 600,
  },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 12 },
  th: {
    position: 'sticky', top: 0,
    textAlign: 'left', padding: '10px 12px',
    background: 'var(--cp-surface-2)', borderBottom: '1px solid var(--cp-border)',
    fontSize: 11, fontWeight: 700, color: 'var(--cp-text-muted)',
    textTransform: 'uppercase', letterSpacing: 0.5, whiteSpace: 'nowrap',
  },
  thNum: {
    position: 'sticky', top: 0,
    textAlign: 'right', padding: '10px 12px',
    background: 'var(--cp-surface-2)', borderBottom: '1px solid var(--cp-border)',
    fontSize: 11, fontWeight: 700, color: 'var(--cp-text-muted)',
    textTransform: 'uppercase', letterSpacing: 0.5, whiteSpace: 'nowrap',
  },
  td: { padding: '8px 12px', borderBottom: '1px solid var(--cp-border)', color: 'var(--cp-text-body)', verticalAlign: 'top' },
  tdNum: { padding: '8px 12px', borderBottom: '1px solid var(--cp-border)', color: 'var(--cp-text-primary)', textAlign: 'right', fontVariantNumeric: 'tabular-nums', verticalAlign: 'top' },
  tdMono: { padding: '8px 12px', borderBottom: '1px solid var(--cp-border)', color: 'var(--cp-text-body)', fontFamily: 'ui-monospace, monospace', fontSize: 11, verticalAlign: 'top' },
  tdMuted: { padding: '8px 12px', borderBottom: '1px solid var(--cp-border)', color: 'var(--cp-text-muted)', textAlign: 'center' },
  tinyMono: { fontSize: 10, color: 'var(--cp-text-muted)', fontFamily: 'ui-monospace, monospace' },
  link: { color: 'var(--cp-accent)', textDecoration: 'none' },

  confDots: { display: 'inline-flex', gap: 3, justifyContent: 'flex-end' },
  confDot: { width: 6, height: 6, borderRadius: '50%', display: 'inline-block' },

  // Archetypes
  archGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: 16 },
  archCard: {
    background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)',
    borderRadius: 10, padding: 20, display: 'flex', flexDirection: 'column', gap: 12,
  },
  archCardHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  archCode: { fontSize: 11, color: 'var(--cp-text-muted)', fontFamily: 'ui-monospace, monospace' },
  archLabel: { fontSize: 16, fontWeight: 700, color: 'var(--cp-text-primary)', lineHeight: '20px' },
  recommendedChip: {
    fontSize: 9, fontWeight: 700, padding: '4px 8px',
    background: 'var(--cp-accent-soft)', color: 'var(--cp-accent)',
    borderRadius: 999, letterSpacing: 0.5,
  },
  archShort: { fontSize: 12, color: 'var(--cp-text-body)', lineHeight: 1.5 },
  archFacts: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 8 },
  fact: {
    padding: '8px 10px',
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    borderRadius: 6,
  },
  factLabel: { fontSize: 9, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 2 },
  factValue: { fontSize: 12, fontWeight: 700, color: 'var(--cp-text-primary)', fontVariantNumeric: 'tabular-nums' },

  archFactorTable: { display: 'flex', flexDirection: 'column', gap: 4, padding: 12, background: 'var(--cp-surface-0)', borderRadius: 8 },
  archFactorTitle: { fontSize: 10, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 4 },
  archFactorRow: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 11 },
  archFactorKey: { width: 80, color: 'var(--cp-text-body)', fontFamily: 'ui-monospace, monospace' },
  archFactorBar: { flex: 1, height: 6, background: 'var(--cp-border)', borderRadius: 3, overflow: 'hidden' },
  archFactorBarFill: { display: 'block', height: '100%', background: 'var(--cp-accent)' },
  archFactorVal: { width: 50, textAlign: 'right', color: 'var(--cp-text-primary)', fontWeight: 600, fontVariantNumeric: 'tabular-nums' },

  archScores: { display: 'flex', gap: 6 },
  archScore: { flex: 1, padding: 6, background: 'var(--cp-surface-0)', borderRadius: 6, textAlign: 'center' },
  archScoreLabel: { fontSize: 9, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  archScoreVal: { fontSize: 12, fontWeight: 700, color: 'var(--cp-text-primary)' },

  archComp: { padding: '8px 12px', background: 'var(--cp-surface-0)', borderRadius: 6, borderLeft: '3px solid var(--cp-accent)' },
  archCompLabel: { fontSize: 9, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5, marginRight: 6 },
  archCompText: { fontSize: 11, color: 'var(--cp-text-body)', fontStyle: 'italic' },

  // GPU
  gpuGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16 },
  gpuCard: {
    background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)',
    borderRadius: 10, padding: 16, display: 'flex', flexDirection: 'column', gap: 10,
  },
  gpuHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' },
  gpuVendor: { fontSize: 11, fontWeight: 700, color: 'var(--cp-text-muted)', letterSpacing: 0.5 },
  gpuSku: { fontSize: 16, fontWeight: 700, color: 'var(--cp-text-primary)' },
  gpuFacts: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 6 },
  gpuNotes: { fontSize: 11, color: 'var(--cp-text-muted)', fontStyle: 'italic', lineHeight: 1.4 },

  // Fit matrix
  fitWrap: { border: '1px solid var(--cp-border)', borderRadius: 10, overflow: 'auto' },

  // DB
  envGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 8 },
  envCell: { padding: 12, background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)', borderRadius: 8 },
  envKey: { fontSize: 10, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  envVal: { fontSize: 13, fontWeight: 700, color: 'var(--cp-text-primary)', marginTop: 2 },

  okChip: {
    fontSize: 10, fontWeight: 700, padding: '2px 8px',
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    color: 'var(--cp-text-body)', borderRadius: 999, letterSpacing: 0.5,
  },
  errChip: {
    fontSize: 10, fontWeight: 700, padding: '2px 8px',
    background: 'var(--cp-accent-soft)', border: '1px solid var(--cp-accent)',
    color: 'var(--cp-accent)', borderRadius: 999, letterSpacing: 0.5,
  },

  // Live trace
  traceControls: { display: 'flex', gap: 8, alignItems: 'flex-end', flexWrap: 'wrap', padding: 16, background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)', borderRadius: 10 },
  traceField: { display: 'flex', flexDirection: 'column', gap: 4 },
  traceLabel: { fontSize: 10, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  traceInput: { height: 36, padding: '0 12px', background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)', borderRadius: 8, color: 'var(--cp-text-primary)', fontSize: 13, width: 100 },
  traceBtn: { height: 36, padding: '0 20px', background: 'var(--cp-accent)', color: 'var(--cp-text-strong)', border: 'none', borderRadius: 8, fontSize: 12, fontWeight: 700, cursor: 'pointer', letterSpacing: 0.3 },

  traceKpis: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 8, marginTop: 16 },
  kpi: { padding: 12, background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)', borderRadius: 8 },
  kpiLabel: { fontSize: 10, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  kpiValue: { fontSize: 18, fontWeight: 700, color: 'var(--cp-text-primary)', fontVariantNumeric: 'tabular-nums', marginTop: 2 },
  kpiHint: { fontSize: 10, color: 'var(--cp-text-muted)', marginTop: 2 },

  details: { marginTop: 16, padding: 12, background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)', borderRadius: 10 },
  summary: { cursor: 'pointer', fontSize: 12, fontWeight: 700, color: 'var(--cp-text-primary)' },
  pre: { fontSize: 11, fontFamily: 'ui-monospace, monospace', color: 'var(--cp-text-body)', overflow: 'auto', maxHeight: 400, margin: '8px 0 0', padding: 12, background: 'var(--cp-surface-0)', borderRadius: 6 },

  // Health tab
  healthAllOk: {
    padding: '20px 24px',
    background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)',
    borderRadius: 10, fontSize: 14, fontWeight: 700, color: 'var(--cp-text-primary)',
  },
  healthGroup: { display: 'flex', flexDirection: 'column', gap: 8 },
  healthGroupHead: { display: 'flex', alignItems: 'center', gap: 8 },
  healthBadge: {
    fontSize: 11, fontWeight: 700, padding: '4px 12px',
    borderRadius: 999, letterSpacing: 0.5,
  },
  healthAreaChip: {
    fontSize: 10, fontWeight: 700, padding: '2px 8px',
    background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)',
    color: 'var(--cp-text-muted)', borderRadius: 999, letterSpacing: 0.5,
    display: 'inline-block',
  },

  // Export buttons
  exportBtn: {
    fontSize: 11, fontWeight: 700, padding: '6px 12px',
    background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)',
    borderRadius: 999, color: 'var(--cp-text-body)',
    cursor: 'pointer', letterSpacing: 0.3, whiteSpace: 'nowrap',
  },
};
