// lib/oracle-intelligence/absorption.js
//
// Sprint 2 — Commercial Absorption Intelligence.
// Pour chaque région stratégique, profil de la demande, de la maturité, des
// risques d'oversupply, de la compression des prix, et de la concentration
// client. Le memo doit utiliser ces estimations pour ne pas surévaluer
// l'occupancy ramp.

export const COMMERCIAL_ABSORPTION = {
  qatar: {
    label: 'Qatar',
    demand_maturity: 'emerging',
    enterprise_velocity: 'low-medium',
    sovereign_anchor: 'high — QIA + Brookfield $20B AI partnership 2024',
    absorption_capacity_mw_year: 80,
    realistic_pipeline_2030_mw: 600,
    oversupply_risk_2027: 'low (supply still gated by power + permits)',
    pricing_compression_risk: 'low — scarcity premium expected to hold +10-15% vs MENA avg',
    customer_concentration_risk: 'high — government anchor likely >70% of first phase',
    key_notes: [
      'Free zone (QFZA) advantage = 6 mo permit vs 24mo elsewhere',
      'KAHRAMAA grid headroom material (~8 GW), but new 50MW connection still 24mo lead',
      'Water-stress drives closed-loop dry cooling premium',
      'Brookfield + QIA partnership is the structural unlock',
    ],
  },
  uae: {
    label: 'UAE',
    demand_maturity: 'maturing-fast',
    enterprise_velocity: 'high',
    sovereign_anchor: 'high — G42 + Microsoft $1.5B + Stargate UAE',
    absorption_capacity_mw_year: 220,
    realistic_pipeline_2030_mw: 2500,
    oversupply_risk_2027: 'medium — multiple operators pursuing same anchors',
    pricing_compression_risk: 'medium — competitive pressure from new entrants',
    customer_concentration_risk: 'high — G42 / Microsoft dominate government + commercial channel',
    key_notes: [
      'DEWA + EWEC grid among cheapest + cleanest in GCC',
      'Khazna = national champion, sets reference pricing',
      'Export-control overlay growing (US chip restrictions)',
      'Falcon LLM + Stargate UAE position UAE as primary regional hub',
    ],
  },
  saudi_arabia: {
    label: 'Saudi Arabia',
    demand_maturity: 'strategic-greenfield',
    enterprise_velocity: 'medium',
    sovereign_anchor: 'very high — Humain ($100B+) + NEOM + Vision 2030',
    absorption_capacity_mw_year: 180,
    realistic_pipeline_2030_mw: 1400,
    oversupply_risk_2027: 'low-medium (government demand backstops; commercial uncertain)',
    pricing_compression_risk: 'low — government anchor sets floor',
    customer_concentration_risk: 'high — Humain / PIF channel dominates',
    key_notes: [
      'NEOM = greenfield, long-build, green H2 anchored',
      'Humain just launched (2024) — early execution risk',
      'SEC grid + Marafiq, 50% renewable target by 2030',
      'Largest government capital pool in GCC',
    ],
  },
  oman: {
    label: 'Oman',
    demand_maturity: 'early',
    enterprise_velocity: 'low',
    sovereign_anchor: 'medium — Duqm SEZ + MC1 Equinix-Omantel JV',
    absorption_capacity_mw_year: 40,
    realistic_pipeline_2030_mw: 300,
    oversupply_risk_2027: 'low',
    pricing_compression_risk: 'low — scarcity benefits incumbents',
    customer_concentration_risk: 'medium',
    key_notes: [
      'Subsea cable advantage (Khor Fakkan + Salalah landings)',
      'Lower energy cost than Qatar/UAE',
      'MC1 Equinix-Omantel JV is the reference',
    ],
  },
  bahrain: {
    label: 'Bahrain',
    demand_maturity: 'maturing (financial-services-led)',
    enterprise_velocity: 'medium',
    sovereign_anchor: 'low — AWS region anchor',
    absorption_capacity_mw_year: 30,
    realistic_pipeline_2030_mw: 250,
    oversupply_risk_2027: 'medium',
    pricing_compression_risk: 'medium',
    customer_concentration_risk: 'medium — financial services + AWS',
    key_notes: [
      'AWS Middle East region anchored 2019',
      'Financial-services compute demand stable',
      'Smaller scale than Qatar/UAE/KSA',
    ],
  },
  kuwait: {
    label: 'Kuwait',
    demand_maturity: 'nascent',
    enterprise_velocity: 'low',
    sovereign_anchor: 'low — New Kuwait 2035, K-AI initiatives early',
    absorption_capacity_mw_year: 20,
    realistic_pipeline_2030_mw: 150,
    oversupply_risk_2027: 'low',
    pricing_compression_risk: 'low',
    customer_concentration_risk: 'high — concentrated public sector demand',
    key_notes: [
      'Smallest GCC compute market today',
      'Government capital available but execution slower',
    ],
  },
  europe: {
    label: 'Europe (aggregate)',
    demand_maturity: 'mature',
    enterprise_velocity: 'high',
    sovereign_anchor: 'medium — Bleu, Delos, GAIA-X',
    absorption_capacity_mw_year: 1200,
    realistic_pipeline_2030_mw: 12000,
    oversupply_risk_2027: 'low (FLAP-D power-constrained)',
    pricing_compression_risk: 'low (supply constrained)',
    customer_concentration_risk: 'medium',
    key_notes: [
      'Nordic green-power campuses cheapest',
      'FLAP-D (Frankfurt, London, Amsterdam, Paris, Dublin) power-constrained',
      'EU AI Act compliance overhead',
    ],
  },
  apac: {
    label: 'APAC (aggregate)',
    demand_maturity: 'mature in JP/SG; emerging IN/ID/VN',
    enterprise_velocity: 'high (varies)',
    sovereign_anchor: 'high in JP/KR/SG',
    absorption_capacity_mw_year: 2200,
    realistic_pipeline_2030_mw: 20000,
    oversupply_risk_2027: 'low',
    pricing_compression_risk: 'low (supply gated by power)',
    customer_concentration_risk: 'low',
    key_notes: [
      'Singapore power-constrained (Green DC roadmap)',
      'Japan + Korea strong government + hyperscaler',
      'India + SEA growth limited by grid',
    ],
  },
  north_america: {
    label: 'North America',
    demand_maturity: 'most-mature',
    enterprise_velocity: 'highest',
    sovereign_anchor: 'low (commercial)',
    absorption_capacity_mw_year: 5000,
    realistic_pipeline_2030_mw: 50000,
    oversupply_risk_2027: 'low (constrained by power + transformers)',
    pricing_compression_risk: 'low',
    customer_concentration_risk: 'high (top hyperscalers dominate)',
    key_notes: [
      'Texas + Virginia + Arizona core',
      'ERCOT / PJM wholesale markets material',
      'Power constraints emerging in NoVA',
    ],
  },
};
