// ui-strings.ts — strings UI cockpit (UI.*).

export const UI = {
  // Navigation
  NAV_RAIL_ARIA: 'Hearst cockpit sections',
  // Demo-first nav wording (Batch 1 IA polish) — visible labels only; routes unchanged.
  // Primary deal journey:
  NAV_SIMULATOR: 'Model',           // /admin/hearst/simulator
  NAV_SOURCES: 'Evidence',          // /admin/hearst/sources
  NAV_DOSSIER: 'Decision',          // /admin/hearst/dossier
  // Analyst tools (secondary):
  NAV_FINANCIAL: 'Underwriting',    // /admin/hearst/financial
  NAV_DEALS: 'Playbook',            // /admin/hearst/deals
  NAV_WORKSPACE: 'Saved scenarios', // /admin/hearst/workspace

  // Actions génériques
  ACTION_SAVE: 'Save',
  ACTION_DELETE: 'Delete',
  ACTION_CANCEL: 'Cancel',
  ACTION_RETRY: 'Retry',
  ACTION_CONFIRM: 'Confirm',
  ACTION_OPEN: 'Open',
  ACTION_EXPORT: 'Export',
  ACTION_GENERATE: 'Generate',

  // Assistant chat (FAB mobile)
  CHAT_OPEN: 'Open assistant',
  CHAT_CLOSE: 'Close assistant',

  // États
  STATE_LOADING: 'Loading…',
  STATE_SAVING: 'Saving…',
  STATE_CALCULATING: 'Calculating…',
  STATE_ERROR: 'An error occurred',

  // Simulator
  SIM_PAGE_EYEBROW: 'Oracle capital cockpit',
  SIM_PAGE_TITLE: 'Investment Simulator',
  SIM_PAGE_SUBTITLE: 'Shape a Qatar AI/data-center thesis from capital, operating model and GPU density.',
  SIM_BUILD_BRIEF_EYEBROW: 'Build brief',
  SIM_BUILD_BRIEF_TITLE: 'Set the investment constraint, then size the machine.',
  SIM_BUILD_BRIEF_HINT: 'Pick how the IC wants to think first: budget, power capacity, or target return. The simulator keeps the downstream scenario coherent.',
  SIM_PANEL_START_EYEBROW: 'Starting Point',
  SIM_PANEL_START_TITLE: 'Choose the control variable',
  SIM_PANEL_SIZE_EYEBROW: 'Project Size / Targets',
  SIM_PANEL_SIZE_TITLE: 'Calibrate the initial scenario',
  // Case setup — page 1 configures assumptions. Results live after Validate.
  SIM_CASE_EYEBROW: 'Scenario setup',
  SIM_CASE_TITLE: 'Configure scenario',
  SIM_CASE_SUBTITLE: 'Choose model, size and technology mix.',
  SIM_CASE_MODEL_LABEL: 'Model',
  SIM_CASE_MARKET_LABEL: 'Market',
  SIM_CASE_SIZE_LABEL: 'Size',
  SIM_CASE_MODE_LABEL: 'Solve by',
  SIM_CASE_EDITORS: 'Inputs',
  SIM_DC_KICKER: 'Scale model',
  SIM_DC_TITLE: '2D campus preview',
  SIM_DC_ARIA: 'Animated two dimensional data center campus preview',
  SIM_DC_GRID: 'Grid',
  SIM_DC_SCALE: 'Capacity',
  SIM_DC_HALLS: 'Halls',
  SIM_DC_AI_FABRIC: 'AI fabric',
  // Why this case — the selected thesis summarised; the 4-card selector is hidden
  // until the user asks to change it.
  SIM_WHY_TITLE: 'Model',
  SIM_THESIS_CHANGE: 'Change thesis',
  SIM_THESIS_DONE: 'Done',
  SIM_SIZE_CHANGE: 'Edit size',
  SIM_SIZE_DONE: 'Done',
  // Section 01 — Investment Thesis (hero). The operating-model archetype, framed
  // as the primary entry decision: what kind of investment is this?
  SIM_THESIS_EYEBROW: 'Step 1 · Investment thesis',
  SIM_THESIS_TITLE: 'Investment Thesis',
  SIM_THESIS_HINT: 'Choose the type of investment. This sets the operating model for everything below.',
  // Section 02 — Investment Size. Grouped investment parameters, not config controls.
  SIM_SIZE_EYEBROW: 'Step 2 · Investment size',
  SIM_SIZE_TITLE: 'Size',
  SIM_SIZE_HINT: 'Set one parameter — budget, capacity or target return. The other two are computed.',
  SIM_SIZE_PARAMS: 'Investment parameters',
  SIM_HW_EYEBROW: 'Step 3 · Technology stack',
  SIM_HW_TITLE: 'Technology',
  SIM_HW_HINT: 'Power mix, rack density and GPU economics',
  SIM_HW_SHOW: 'Show details',
  SIM_HW_HIDE: 'Hide details',
  SIM_HW_COLLAPSED_NOTE: 'Optional — defaults to a balanced mix. Open to tune GPU allocation, rack density and topology.',
  SIM_READY_SCENARIOS: 'Ready scenarios',
  SIM_WHAT_TO_CHANGE: 'Solve by',
  SIM_INPUT_MODE_ARIA: 'Input mode',
  // Brief Bar — single control object (mode segments + driven field + computed results)
  SIM_QUICK_START: 'Quick start',
  SIM_QUICK_START_COUNT: (n: number) => `${n} templates`,
  SIM_MODE_BUDGET: 'Budget',
  SIM_MODE_SIZE: 'Size',
  SIM_MODE_RETURN: 'Target return',
  SIM_MODE_BUDGET_UNIT: '$',
  SIM_MODE_SIZE_UNIT: 'MW',
  SIM_MODE_RETURN_UNIT: '%',
  SIM_FIELD_BUDGET_LABEL: 'Money to invest',
  SIM_FIELD_SIZE_LABEL: 'Target capacity',
  SIM_FIELD_RETURN_LABEL: 'Yearly return target',
  SIM_FIELD_BUDGET_DESC: 'Total money to invest (USD). The engine estimates buildable capacity.',
  SIM_FIELD_SIZE_DESC: 'Target power capacity for the deal.',
  SIM_FIELD_RETURN_DESC: 'The engine works backwards from your return target (default lever: pricing).',
  SIM_FIELD_BUDGET_PLACEHOLDER: '500,000,000',
  SIM_FIELD_SIZE_PLACEHOLDER: '50',
  SIM_FIELD_RETURN_PLACEHOLDER: '18',
  SIM_AUTOFILL: 'Auto-fill with Qatar market data →',
  SIM_YOUR_CHOICE: 'Your choice',
  SIM_COMPUTED: 'Computed',
  SIM_RESULT_BUDGET: 'Budget',
  SIM_RESULT_SIZE: 'Size',
  SIM_RESULT_RETURN: 'IRR (annual)',
  SIM_RESULT_RETURN_NOTE: 'levered equity · pre-tax',
  SIM_RESULT_RETURN_LONG: 'Target Return',
  SIM_RESULT_PENDING: 'Run to compute',
  SIM_SOLVER_NO_SOLUTION: 'No solution — try a smaller target or another lever.',
  SIM_SOLVER_SOLVED: (n: number) => `Solved in ${n} steps`,
  SIM_LEVER_LABEL: 'What to change',
  SIM_LEVER_PRICING: 'Pricing',
  SIM_LEVER_CAPEX: 'Build cost',
  SIM_LEVER_LEVERAGE: 'Debt level',
  SIM_LEVER_MW: 'Size (MW)',
  // Configuration card
  SIM_CONFIG_EYEBROW: 'CONFIGURATION',
  SIM_CONFIG_MODEL_LABEL: 'Operating Model',
  SIM_CONFIG_HW_LABEL: 'Hardware Mix',
  SIM_CONFIG_GENERATE_MEMO: 'Generate Investment Memo',
  SIM_CONFIG_FINETUNE_SHOW: 'Tune power density per rack',
  SIM_CONFIG_FINETUNE_HIDE: 'Hide rack density controls',
  SIM_INVESTMENT_STRUCTURE_TITLE: 'Investment structure',
  SIM_INVESTMENT_STRUCTURE_PILL: 'QIA + Hearst → Equinix',
  SIM_CASE_VERB: 'Deploy',
  SIM_CASE_INTO: 'into',
  SIM_CASE_IN_QATAR_WITH: 'in Qatar with',
  SIM_METRIC_CAPITAL: 'Capital',
  SIM_METRIC_CAPACITY: 'Capacity',
  SIM_METRIC_MOIC: 'MOIC',
  SIM_TIMELINE_START: 'Investment start',
  SIM_TIMELINE_COD: 'COD / operations',
  SIM_TIMELINE_EXIT: 'Exit model',
  SIM_JV_PARTY_QIA: 'QIA',
  SIM_JV_PARTY_HEARST: 'Hearst',
  SIM_JV_QIA_ROLE: 'Anchor capital',
  SIM_JV_HEARST_ROLE: 'Founder / sponsor',
  SIM_JV1_LABEL: 'JV1',
  SIM_JV1_NAME: 'QIA + Hearst vehicle',
  SIM_JV_SHARE_QIA_HEARST: 'QIA + Hearst',
  SIM_JV_SHARE_EQUINIX: 'Equinix',
  SIM_JV_NOTE: 'Equinix co-invests and operates the campus. The strategic vehicle remains QIA + Hearst first.',
  SIM_ELECTRICITY_UNIT: '$/MWh',
  SIM_MODEL_HELD_TITLE: 'Model-held assumptions',
  SIM_MODEL_HELD_HINT: 'Shown for transparency, not user inputs.',
  SIM_ASSUMPTION_CONSTRUCTION_LABEL: 'Construction cost',
  SIM_ASSUMPTION_CONSTRUCTION_VALUE: 'Auto-sourced from market comps',
  SIM_ASSUMPTION_EXIT_LABEL: 'Exit year',
  SIM_ASSUMPTION_EXIT_VALUE: 'Derived from start + COD + hold',
  SIM_ASSUMPTION_PUE_LABEL: 'PUE',
  SIM_ASSUMPTION_PUE_VALUE: 'Model benchmark, not a user lever',
  SIM_ASSUMPTION_RESERVATION_LABEL: 'Reservation',
  SIM_ASSUMPTION_RESERVATION_VALUE: '80% reserved capacity',
  SIM_ASSUMPTION_USAGE_LABEL: 'Multitenant usage',
  SIM_ASSUMPTION_USAGE_VALUE: '100% actual consumption',
  SIM_ELECTRICITY_LABEL: 'Tenant electricity cost',
  SIM_ELECTRICITY_DESC: 'Kept visible because it matters commercially, even when passed through.',
  SIM_ELECTRICITY_ARIA: 'Tenant electricity cost in dollars per megawatt hour',
  SIM_ELECTRICITY_NOTE: 'For powered-shell and operator-led structures, tenant power is passed through. The model uses this value to keep the Qatar advantage visible without asking users to tune PUE or construction inputs.',
  // Archetypes (Deal Structures)
  ARCH_POWERED_SHELL_LABEL: 'Shell + Long Lease',
  ARCH_POWERED_SHELL_SHORT: 'We build it, a big operator rents it for 15-20 years',
  ARCH_BRANDED_JV_LABEL: 'Co-branded Joint Venture (51 / 49)',
  ARCH_BRANDED_JV_SHORT: 'We own 51%, an operator owns 49%, both names on the building',
  ARCH_MANAGE_ONLY_LABEL: 'In-House (Outsourced Operations)',
  ARCH_MANAGE_ONLY_SHORT: 'We own 100%, an outside team runs the daily operations',
  ARCH_WHITE_LABEL_LABEL: 'Hidden Operator',
  ARCH_WHITE_LABEL_SHORT: 'We are the public brand, an invisible partner runs the building',
  ARCH_SALE_LEASEBACK_LABEL: 'Build & Sell',
  ARCH_SALE_LEASEBACK_SHORT: 'We build it, sell once stabilized, optionally lease part back',
  ARCH_NEOCLOUD_GPU_LABEL: 'GPU Rental Cloud (CoreWeave-style)',
  ARCH_NEOCLOUD_GPU_SHORT: 'We own both the building and the AI chips, and rent computing power by the hour',
  ARCH_HYPERSCALER_LABEL: 'Tech Giant Partnership (Minority Stake)',
  ARCH_HYPERSCALER_SHORT: 'We invest 15-30% in a data center built and run by AWS, Google, or Meta',
  ARCH_SOVEREIGN_AI_LABEL: 'Government AI Cluster',
  ARCH_SOVEREIGN_AI_SHORT: 'A dedicated AI center for the Qatar government, 10-15 year contract',
  // Archetype Descriptions
  ARCH_POWERED_SHELL_DESC: 'We build the empty data center (walls, power, land). A big operator like Equinix moves in, equips it, and pays rent for 15-20 years. We keep ownership and our name on the building. Lowest risk, steady rent. Closest example: Meta x Blue Owl Hyperion ($27B, 2025).',
  ARCH_BRANDED_JV_DESC: 'We team up with an operator like Equinix. We put in 51% of the money, they put in 49%. Both names appear on the building. They run the day-to-day, we keep board control. Rare in practice (closest: Equinix x Omantel MC1 Oman, 2020, but operator brand dominates).',
  ARCH_MANAGE_ONLY_DESC: 'We own the entire building and sign customers ourselves. A specialist company (like Schneider or Vertiv) is paid a fixed fee (around 10-15% of revenue) to handle maintenance, security and monitoring. We get all the upside but also carry all the risk of filling the building.',
  ARCH_WHITE_LABEL_DESC: 'We own 100% and are the only brand customers see. A specialist partner runs the building in the background without ever appearing publicly. Customers (Microsoft, Oracle, etc.) sign contracts directly with us. Partner is paid like a service provider (around 20% of revenue). Same model as Compass Datacenters.',
  ARCH_SALE_LEASEBACK_DESC: 'We build the data center, then sell it to an infrastructure investor or operator once it is filled with customers. Big one-time payout, but we exit the long-term story. Goes against our brand goal — included as a fallback only if the Qatar mandate becomes politically difficult.',
  ARCH_NEOCLOUD_GPU_DESC: 'We own the building AND the AI chips inside. We rent computing power by the hour to AI labs, startups and large companies. Direct competitor to CoreWeave and Lambda. Highest revenue but short customer contracts (1-3 years) and chips need replacing every 18-24 months. Cheap Qatar electricity (~$32/MWh) protects our margins.',
  ARCH_HYPERSCALER_DESC: 'We invest as a minority partner (15-30%) in a data center that a tech giant (AWS, Google, Meta) builds and runs in Qatar. We collect dividends and a capital gain when we exit. No control, no brand visibility. Best for steady financial returns, but we lose the strategic story.',
  ARCH_SOVEREIGN_AI_DESC: 'An AI center built specifically for the Qatar government and its agencies (QIA, Qai, defense, ministries). Contract lasts 10-15 years at a negotiated price (usually our cost plus 15-20%). One customer means no risk of empty space. Our brand becomes linked to Qatar national tech independence. Steady margin, but growth limited to government budget.',
  // Archetype Terms & Comps
  ARCH_POWERED_SHELL_TERMS: [
    'Our name stays on the building. Operator only gets a small interior panel.',
    'Lease lasts 15-20 years, with 3% yearly rent increases.',
    'No exclusive deal — we stay free to bring other operators into nearby buildings.',
    'We can exit the lease if the operator gets bought out or delisted.',
  ],
  ARCH_POWERED_SHELL_COMP: 'Meta x Blue Owl Hyperion (Oct 2025) — $27B / Blue Owl owns 80% / Meta leases 100% for ~15 yr.',
  ARCH_BRANDED_JV_TERMS: [
    'Both names on the building — lock our name in first position in the contract.',
    'We pick the CEO and Chair, partner picks the CFO and COO. We approve any building sale.',
    'Clear exit rules so the partner cannot block us when we want to sell.',
    'Banks charge slightly more for the loan because the partner only covers part of the deal.',
  ],
  ARCH_BRANDED_JV_COMP: 'Equinix x Omantel MC1 Oman (2020) — operating JV, but brand stays "Equinix MC1".',
  ARCH_MANAGE_ONLY_TERMS: [
    'Hard service targets (uptime, response time, energy efficiency) with fee penalties if missed.',
    'We can swap the operations partner with 12 months notice — no lock-in.',
    'We need to build our own sales team and customer relationships before opening.',
    'Banks ask for stronger guarantees because no big operator covers the loan.',
  ],
  ARCH_MANAGE_ONLY_COMP: 'Multiple GCC government DCs use Schneider/Vertiv on O&M-only contracts.',
  ARCH_WHITE_LABEL_TERMS: [
    'Partner signs an NDA — cannot mention us as a client publicly.',
    'All customer contracts are signed directly by us — the partner is a subcontractor.',
    'Tech upgrades for next-gen AI chips are included in the operations contract.',
    'Compass (owned by Brookfield) is the preferred partner — leverages our Brookfield relationship.',
  ],
  ARCH_WHITE_LABEL_COMP: 'Compass Datacenters (Brookfield/OTPP, $5.5B acq. 2023) — 800 MW operated white-label for hyperscalers.',
  ARCH_SALE_LEASEBACK_TERMS: [
    'WARNING: kills our brand presence. Only use as a backup if politics force an exit.',
    'Wait until the building is at least 80% full before selling — usually 3 to 4 years after opening.',
    'Sale price depends on yield expectations (around 6-8% in top markets, 7-9% in frontier markets).',
    'Qatar charges tax on the gain — work with the Qatar Free Zone authority to optimize.',
  ],
  ARCH_SALE_LEASEBACK_COMP: 'Iron Mountain DC acquisitions; numerous tier-2 developer exits to Blackstone/KKR.',
  ARCH_NEOCLOUD_GPU_TERMS: [
    'Customer contracts last 1 to 3 years — mix of reserved clusters and on-demand usage.',
    'Replace chips every 24 months — older chips lose 40-60% of value over 3 years.',
    'Need high-quality fiber connectivity (via Equinix or Ooredoo).',
    'Customer mix: ~40% AI labs, ~40% enterprise AI, ~20% government AI training.',
  ],
  ARCH_NEOCLOUD_GPU_COMP: 'CoreWeave $19B IPO (Q1 2025) — 500MW GPU cloud. Lambda Series D 2024 = $300M valued ~$2.5B.',
  ARCH_HYPERSCALER_TERMS: [
    'We own 15-30%, the tech giant owns 70-85% and makes all the decisions.',
    'Annual dividends of around 7-9% on the money we put in.',
    'No board seat (maybe one observer). No say in commercial decisions.',
    'We can exit alongside the tech giant when they sell at a typical valuation of 18-22x profit.',
  ],
  ARCH_HYPERSCALER_COMP: 'Saudi-PIF in AWS Riyadh (announced 2024) — minority infrastructure stake.',
  ARCH_SOVEREIGN_AI_TERMS: [
    'Single customer: Qatar Gov / Qai / defense. 10-15 year guaranteed contract.',
    'Fully isolated from the public internet, military-grade encryption.',
    'Strict compliance: Qatar data protection law, GDPR-equivalent, plus US defense rules for defense use.',
    'Hard to sell later: Qatar Gov has first refusal on any sale. Natural buyers are Brookfield or Qai.',
  ],
  ARCH_SOVEREIGN_AI_COMP: 'UAE G42 national AI ($1.5B Microsoft 2024); Saudi HUMAIN PIF (2024).',
  // Hardware Allocation — presets, tiers, KPIs, deployment readout, advanced controls
  HW_PRESET_COLO_NAME: 'Classic Colocation',
  HW_PRESET_COLO_TAGLINE: 'Mostly standard racks, little AI',
  HW_PRESET_COLO_INFO: 'Mostly ordinary servers (about 80%) with only a little AI hardware. Air-cooled, cheaper to build, and easy to rent to a wide range of tenants. Lower revenue per megawatt than AI, but the steadiest and least risky way to fill the building.',
  HW_PRESET_MIXED_NAME: 'Mixed AI-Ready',
  HW_PRESET_MIXED_TAGLINE: 'Balanced colo + AI capacity',
  HW_PRESET_MIXED_INFO: 'A balanced split — roughly 40% standard, 35% dense, 25% AI. Part of the site runs ordinary servers while part is built for AI chips with liquid cooling. Captures higher AI pricing without betting the whole project on AI demand.',
  HW_PRESET_AI_NAME: 'AI Factory',
  HW_PRESET_AI_TAGLINE: 'GPU-dense, liquid-cooled',
  HW_PRESET_AI_INFO: 'Built almost entirely for AI (about 70%), packed with GPUs and liquid-cooled to handle the heat. The highest revenue per megawatt, but the most expensive to build and the most exposed to swings in AI demand and chip prices.',
  HW_TIER_STANDARD_NAME: 'Standard',
  HW_TIER_STANDARD_META: 'low power · ≤15 kW/rack',
  HW_TIER_DENSE_NAME: 'High-density',
  HW_TIER_DENSE_META: 'medium power · ≤60 kW/rack',
  HW_TIER_AI_NAME: 'AI clusters',
  HW_TIER_AI_META: 'very high power · ≥70 kW/rack',
  HW_KPI_CHIPS: 'AI chips',
  HW_KPI_RACKS: 'Racks',
  HW_KPI_EQUIP: 'Equipment cost',
  HW_KPI_REVENUE: 'AI revenue / yr',
  HW_DEPLOY_KICKER: 'Deployment',
  HW_DEPLOY_TITLE: (sku: string) => `${sku} map`,
  HW_AI_BADGE: (pct: number) => `${pct}% AI`,
  HW_READOUT_TOTAL: 'Total power',
  HW_READOUT_AI: 'AI fabric',
  HW_READOUT_RACKS: 'Racks implied',
  HW_MIX_STANDARD: 'Standard',
  HW_MIX_DENSE: 'Dense',
  HW_MIX_AI: 'AI',
  HW_ADV_SHOW: 'Tune GPU and power assumptions',
  HW_ADV_HIDE: 'Hide advanced controls',
  HW_ADV_POWER_TITLE: 'Power density per rack',
  HW_ADV_POWER_META: '(total 100%)',
  HW_ADV_AI_TITLE: 'AI chip',
  HW_ADV_AI_META: (mw: string) => `(${mw} MW dedicated)`,
  HW_ADV_UTILIZATION: 'Utilization',
  HW_ADV_PRICE: '$/hr',
  HW_POWER_HALL: 'Power hall',
  HW_AI_FABRIC: 'AI fabric',
  B2B_TH_CORNER: 'What we sell',
  HW_TOPOLOGY_ARIA: 'Hardware allocation topology',
  HW_GPU_UTIL_ARIA: 'AI chip utilization percentage',
  SIM_VALIDATE: 'Validate & see results →',
  SIM_SAVING: 'Saving…',
  SIM_SAVING_SCENARIO: 'Saving your scenario…',
  SIM_READY: 'Configuration ready.',
  SIM_FILL: 'Fill in your numbers to run the simulation.',
  SIM_FIX_ERROR: 'Fix the error above to continue.',
  SIM_PROJECT_UNAVAILABLE: 'Project unavailable — see error above.',
  SIM_LOADING_PROJECT: 'Resolving project…',
  RESULTS_LOADING_SCENARIO: 'Running scenario…',
  RESULTS_LOADING_ECOSYSTEM: 'Loading industry players…',
  RESULTS_LOADING_SANKEY: 'Loading money flow…',
  RESULTS_SCENARIO_SAVED: 'Scenario already saved',
  RESULTS_RISK_NOTE: 'Debt coverage sits below returns in the hierarchy.',
  RESULTS_CTA_FILL: 'Fill in your numbers to generate a plan',
  RESULTS_CTA_PLAN_READY: 'Plan ready',
  RESULTS_CTA_PLAN_REVIEW: 'Plan needs review',
  RESULTS_CTA_EXPORT: 'Export Summary',
  RESULTS_CTA_SAVE: 'Save Scenario',
  RESULTS_CTA_MEMO: 'Generate Strategic Memo',
  RESULTS_VERDICT_INSUFFICIENT: 'Insufficient data',
  RESULTS_VERDICT_NO_DATA: 'NO DATA',

  // Results (inline simulator + /results route)
  RESULTS_BACK_EDIT: '← Edit inputs',
  RESULTS_BM_CAPEX: 'Total CAPEX',
  RESULTS_BM_CAPEX_NOTE: 'Build requirement',
  RESULTS_BM_EBITDA: 'Stabilized EBITDA',
  RESULTS_BM_EBITDA_NOTE: 'Operating yield',
  RESULTS_BM_PAYBACK: 'Payback',
  RESULTS_BM_PAYBACK_NOTE: 'Capital recovery',
  RESULTS_BM_REVENUE: 'Stabilized revenue',
  RESULTS_BM_REVENUE_NOTE: 'Annual run-rate',
  RESULTS_BM_SOURCE: 'Source score',
  RESULTS_BM_SOURCE_NOTE: 'Evidence depth',
  RESULTS_BM_TERMINAL: 'Terminal value',
  RESULTS_BM_TERMINAL_NOTE: 'Exit valuation',
  RESULTS_CHIP_AI_SUFFIX: 'AI allocation',
  RESULTS_CHIP_NEEDS_REVIEW: (n: number) => `Needs review${n > 1 ? ` (${n})` : ''}`,
  RESULTS_DECISION_METRICS: 'Decision metrics',
  // Decision-first header (UI V2 — presentation only)
  RESULTS_DECISION_APPROVE: 'APPROVE',
  RESULTS_DECISION_REVIEW: 'REVIEW',
  RESULTS_DECISION_REJECT: 'REJECT',
  RESULTS_DECISION_EYEBROW: 'Investment decision',
  RESULTS_CASE_DEPLOY: (capex: string) => `Deploy ${capex}`,
  RESULTS_KPI_MOIC: 'MOIC',
  RESULTS_KPI_NPV: 'NPV',
  RESULTS_KPI_CAPITAL: 'Capital',
  RESULTS_KPI_CAPITAL_NOTE: 'Total CAPEX deployed',
  RESULTS_TV_WARNING: (pct: number) =>
    `Terminal-value dependent — ${pct}% of equity value rides on the exit multiple.`,
  RESULTS_RC_TITLE: 'Returns composition',
  RESULTS_RC_OPERATIONS: 'Operations',
  RESULTS_RC_TERMINAL: 'Terminal value',
  RESULTS_RC_UNAVAILABLE: 'Returns composition unavailable.',
  ADVISOR_RC_DILIGENCE: 'Stress the exit multiple from 18x to 12x and 8x.',
  RESULTS_DM_IRR: 'IRR (Post-tax)',
  RESULTS_DM_IRR_NOTE: 'annualized levered equity return, net of tax',
  RESULTS_DM_MOIC: 'MOIC (Post-tax)',
  RESULTS_DM_MOIC_NOTE: 'levered equity cash multiple at exit, net of tax',
  RESULTS_DM_NPV: 'NPV (Post-tax)',
  RESULTS_DM_NPV_NOTE: 'value created today, net of tax',
  RESULTS_DM_PRETAX_PREFIX: 'Pre-tax',
  RESULTS_DONUT_LABEL: 'Capital',
  RESULTS_DONUT_VALUE: 'Stack',
  RESULTS_ECON_HINT: 'Scale, yield and evidence quality behind the return.',
  RESULTS_ECON_TITLE: 'Economics behind the decision',
  RESULTS_HERO_FALLBACK_NAME: 'Scenario Results',
  RESULTS_CAPITAL_STRUCTURE: 'Structure',
  RESULTS_IM_BUILD_COST: 'Build cost',
  RESULTS_IM_DSCR: 'DSCR risk guardrail',
  RESULTS_IM_EQUITY_IDC: 'Equity (incl. IDC)',
  RESULTS_IM_EXIT_LABEL: 'Exit year',
  RESULTS_IM_EXIT_YEAR: (y: number) => `Year ${y}`,
  RESULTS_IM_IDC: 'Interest during construction',
  RESULTS_IM_OCCUPANCY: 'Occupancy target',
  RESULTS_IM_TERMINAL: 'Terminal value',
  RESULTS_IM_TERMINAL_EQUITY: 'Terminal value (to equity)',
  RESULTS_LAYERS_HINT: 'Starting point, operating model and hardware allocation',
  RESULTS_LAYERS_TITLE: 'Scenario Layers',
  RESULTS_LAYER_HW: 'Hardware Allocation',
  RESULTS_LAYER_INDUSTRY: 'Industry Layer',
  RESULTS_LAYER_MODEL: 'Operating Model',
  RESULTS_LAYER_START: 'Starting Point',
  RESULTS_PROJ_EYEBROW: 'Main analysis',
  RESULTS_PROJ_HINT: '10-year cash generation, break-even path and exit value.',
  RESULTS_PROJ_TITLE: 'Financial Projection',
  RESULTS_RISK_GUARDRAIL: 'Risk guardrail',
  RESULTS_ROW_AI: 'AI exposure',
  RESULTS_ROW_BUSINESS: 'Business',
  RESULTS_ROW_CLIENT: 'Client',
  RESULTS_ROW_GPU: 'GPU SKU',
  RESULTS_ROW_MIX: 'Standard / dense / AI',
  RESULTS_ROW_MODE: 'Mode',
  RESULTS_ROW_MODEL: 'Model',
  RESULTS_ROW_POWER: 'Total power',
  RESULTS_ROW_PUE: 'PUE',
  RESULTS_ROW_REGION: 'Region',
  RESULTS_ROW_THESIS: 'Operating thesis',
  RESULTS_ROW_UTIL: 'Utilization',
  RESULTS_STACK_BROOKFIELD: 'Brookfield equity',
  RESULTS_STACK_DEBT: 'Debt',
  RESULTS_STACK_HEARST: 'HEARST equity',
  RESULTS_STACK_QATAR: 'Qatar equity',
  RESULTS_TIMELINE_HINT: 'Pre-COD development, then operations to exit',
  RESULTS_TIMELINE_TITLE: 'Deployment Timeline',
  GANTT_TRACK_PRE: 'Before COD',
  GANTT_TRACK_PRE_HINT: 'Permits, then construction — bars share one COD-aligned scale',
  GANTT_TRACK_OPS: 'After COD',
  GANTT_TRACK_OPS_HINT: 'Lease-up, stabilized ops and exit',
  GANTT_COD_NOTE: 'Month 0 = commercial operations date (COD). Both panels meet at COD.',
  GANTT_TICK_KICKOFF: 'Kickoff',
  GANTT_TICK_COD: 'COD',
  GANTT_TICK_BEFORE_COD: (mo) => `−${mo} mo`,
  GANTT_TICK_EXIT: (year) => `Y${year} exit`,
  GANTT_META_COD: (months) => `COD offset ${months} months`,
  GANTT_META_EXIT: (year) => `Exit year ${year}`,
  GANTT_RANGE_MO: (n) => `${n} mo`,
  GANTT_RANGE_YR: (y0, y1) => `Y${y0}–Y${y1}`,
  GANTT_RANGE_TAIL: (y) => `Y${y} tail`,
  GANTT_PHASE_PERMITS: 'Permits',
  GANTT_PHASE_PERMITS_DESC: 'Site control, permits, utility coordination',
  GANTT_PHASE_CONSTRUCTION: 'Construction',
  GANTT_PHASE_CONSTRUCTION_DESC: 'Shell, power, cooling and commissioning',
  GANTT_PHASE_LEASEUP: 'Lease-up',
  GANTT_PHASE_LEASEUP_DESC: 'Customer ramp and occupancy build-up',
  GANTT_PHASE_STABILIZED: 'Stabilized operations',
  GANTT_PHASE_STABILIZED_DESC: 'Run-rate revenue and steady operations',
  GANTT_PHASE_EXIT: 'Exit / refinance',
  GANTT_PHASE_EXIT_DESC: 'Refinance or sale window',
  RESULTS_VERDICT_INVESTMENT_GRADE: 'Investment-grade case',
  RESULTS_VERDICT_PENDING: 'Scenario pending',
  RESULTS_VERDICT_REWORK: 'Needs rework before IC',
  RESULTS_VERDICT_VIABLE: 'Viable, needs structuring',
  RESULTS_VIZ_HINT: 'Switch between strategic, industry and money-flow views',
  RESULTS_VIZ_MATRIX_DETAIL: 'Highlights which product layer and customer segment this scenario is really built for.',
  RESULTS_VIZ_MATRIX_LABEL: 'Industry layers',
  RESULTS_VIZ_MATRIX_TITLE: 'Commercial fit by product and buyer',
  RESULTS_VIZ_NETWORK_DETAIL: 'Shows the operators, hyperscalers, capital partners and local enablers around the scenario.',
  RESULTS_VIZ_NETWORK_LABEL: 'Industry players',
  RESULTS_VIZ_NETWORK_TITLE: 'Industry participant network',
  RESULTS_VIZ_RADAR_DETAIL: 'Compares brand control, bankability, speed, margin and exit liquidity.',
  RESULTS_VIZ_RADAR_LABEL: 'Strengths',
  RESULTS_VIZ_RADAR_TITLE: 'Operating-model strength map',
  RESULTS_VIZ_SANKEY_DETAIL: 'Traces equity, debt, build cost, revenue, operating costs and owner profit.',
  RESULTS_VIZ_SANKEY_LABEL: 'Money flow',
  RESULTS_VIZ_SANKEY_TITLE: 'Capital and annual cash-flow path',
  RESULTS_VIZ_TITLE: 'Visualizations',

  // Deals
  DEALS_NAV_ARIA: 'Deal models sections',
  DEALS_CALLOUT_SOVEREIGN: 'The sovereign rule',
  DEALS_CALLOUT_LOCAL: 'Implication for a local deal (a hub like Futur One)',
  DEALS_CLOSING_BOLD: 'The central reflex:',
  DEALS_CLOSING_BODY: 'value is not captured at the equity line alone. The operator keeps 20% but pockets recurring development + operations fees, and whoever holds land + power controls the bottleneck. Knowing which role you play determines what you negotiate.',

  // Workspace (scenarios only — reports → Dossier)
  WS_PAGE_TITLE: 'Workspace',
  WS_SECTION_SCENARIOS: 'Saved scenarios',
  WS_STATUS_ACTIVE: 'Active',
  WS_STATUS_SAVED: 'Saved',
  WS_OPEN_IN_SIMULATOR: 'Open in Simulator →',
  WS_TH_NAME: 'Name',
  WS_TH_TYPE: 'Type',
  WS_TH_CREATED: 'Created',
  WS_TH_STATUS: 'Status',
  WS_PAGE_SUBTITLE: 'Saved scenarios for this project. Reopen in the Simulator; strategic reports live in',
  WS_NO_SCENARIOS: 'No saved scenarios yet. Build one in the Simulator and click "Save this plan".',
  WS_NO_REPORTS: 'No reports yet. Generate a strategic memo from the Simulator.',
  WS_DELETE_CONFIRM: (name: string) => `Delete scenario "${name}"? This cannot be undone.`,

  // Sources
  SOURCES_IN_MODEL: 'In model',
  SOURCES_OPEN_URL: 'Open source URL',
  SOURCES_LOADING: 'Loading market intelligence…',
  SOURCES_MY_SECTION: 'MY SOURCES — Admin & Project-specific',
  SOURCES_NO_DATA: 'No sources found.',
  SOURCES_NO_ADMIN: 'No admin sources yet.',
  SOURCES_NO_FILTER: 'No results matching filters.',
  SOURCES_ADD: 'Add source',
  SOURCES_UIM_TITLE: 'Add to Source Ledger',
  SOURCES_UIM_HINT: 'This flags the source as used in the model — the simulator will use its value for this metric (overriding the benchmark median).',
  SOURCES_UIM_SCENARIO_LABEL: 'Scenario context (for audit)',
  SOURCES_UIM_DONE: 'Source added.',
  SOURCES_UIM_ADD_BTN: 'Add to Ledger',
  SOURCES_UIM_ADDING: 'Adding…',
  SOURCES_UIM_ERR: 'Could not add source to ledger.',
  SOURCES_ACTION_ERR: (msg: string) => msg || 'Action failed.',
  SOURCES_DELETE_CONFIRM: 'Delete this source? This cannot be undone.',

  // Dossier
  DOSSIER_NO_REPORTS: 'No reports for this scenario yet. Generate a strategic memo from the',
  DOSSIER_NO_SCENARIO_REPORTS: 'No reports for this scenario yet.',
  DOSSIER_LOADING_MEMOS: 'Loading memos…',
  DOSSIER_NO_RISKS: 'No risks logged.',
  DOSSIER_NO_VERSIONS: 'No versions.',
  DOSSIER_GO_SIMULATOR: 'the Simulator',
  DOSSIER_EYEBROW_CONDITIONS: 'Conditions before approval',
  DOSSIER_EYEBROW_PEERS: "Why peers aren't directly comparable",
  DOSSIER_VERDICT_NOTE: 'Synthesized from return, risk, freshness & confidence signals',
  DOSSIER_PLACEHOLDER_STACK: 'Capital structure not available for this memo version',
  DOSSIER_PLACEHOLDER_TIMELINE: 'Deployment timeline not available for this memo version',
  DOSSIER_PLACEHOLDER_COMPARABLES: 'No comparable peers cited in this memo version',
  DOSSIER_PLACEHOLDER_RISKS: 'No risks logged for this memo version',
  DOSSIER_RISK_WHY: 'Why it matters ·',
  // Dossier — page chrome
  DOSSIER_PAGE_TITLE: 'Project Dossier',
  DOSSIER_PAGE_SUBTITLE: 'Decision-first strategic reports · versioned · exportable. Open any report for its Decision Canvas.',
  DOSSIER_KPI_REPORTS: 'Reports',
  DOSSIER_KPI_APPROVED: 'Approved',
  DOSSIER_KPI_SCENARIOS: 'Scenarios',
  DOSSIER_LOADING_FALLBACK: 'Loading…',
  DOSSIER_LOADING_SCENARIO: 'Loading scenario…',
  DOSSIER_LOADING_MEMO: 'Loading memo…',
  DOSSIER_BREADCRUMB_ALL_MEMOS: 'All memos',
  DOSSIER_BREADCRUMB_SCENARIO: 'Scenario',
  DOSSIER_REPORT_VERSIONS: (n: number) => `${n} report version${n !== 1 ? 's' : ''}`,
  // Dossier — canvas eyebrows / section heads
  DOSSIER_EYEBROW_VERDICT: 'Investment verdict',
  DOSSIER_EYEBROW_OPPORTUNITY: 'Opportunity type',
  DOSSIER_EYEBROW_NEXT_ACTION: 'Next action',
  DOSSIER_EYEBROW_EQUITY_SPONSORS: 'Equity sponsors',
  DOSSIER_EYEBROW_TRADEOFFS: 'Trade-offs',
  DOSSIER_EYEBROW_SPECULATIVE: 'Speculative branches · low visibility',
  DOSSIER_EYEBROW_DECISION_TENSIONS: 'Decision tensions',
  DOSSIER_EYEBROW_GEN_METADATA: 'Generation metadata',
  DOSSIER_EYEBROW_FULL_JSON: 'Full memo JSON',
  DOSSIER_EYEBROW_VERSIONS: 'Versions',
  DOSSIER_SECTION_RECOMMENDATION: 'Recommendation',
  DOSSIER_SECTION_TOP_RISKS: 'Top risks',
  DOSSIER_RISKS_HINT: (n: number) => `${n} shown`,
  DOSSIER_SECTION_VISUAL_STORY: 'Visual story',
  DOSSIER_SECTION_VISUAL_STORY_HINT: 'from existing projection data',
  DOSSIER_SECTION_ANALYTICS: 'Analytics',
  DOSSIER_SECTION_ANALYTICS_HINT: 'full written memo · continuous',
  // Dossier — analytics blocks
  DOSSIER_BLOCK_STRATEGIC_CONTEXT: 'Strategic context',
  DOSSIER_BLOCK_FINANCIAL_METRICS: 'Financial metrics',
  DOSSIER_BLOCK_INFRASTRUCTURE: 'Infrastructure',
  DOSSIER_BLOCK_MARKET_BENCHMARKING: 'Market benchmarking',
  DOSSIER_BLOCK_REVENUE_MODEL: 'Revenue Model',
  DOSSIER_BLOCK_LONG_TERM_VALUE: 'Long-term value',
  DOSSIER_BLOCK_SOURCES: 'Sources',
  // Dossier — visual story viz titles
  DOSSIER_VIZ_CAPITAL_STACK: 'Capital stack',
  DOSSIER_VIZ_DEPLOYMENT_TIMELINE: 'Deployment timeline',
  DOSSIER_VIZ_BENCHMARK_POSITION: 'Benchmark position',
  DOSSIER_VIZ_CASHFLOW_TRAJECTORY: 'Cashflow trajectory',
  // Dossier — appendix
  DOSSIER_APPENDIX_LABEL: 'Appendix · raw detail, metadata & audit',
  // Dossier — buttons / governance
  DOSSIER_BTN_EXPORT_PDF: 'Export PDF',
  DOSSIER_BTN_MARK_REVIEWED: 'Mark reviewed',
  DOSSIER_BTN_APPROVE: 'Approve',
  DOSSIER_BTN_SEND_BACK: 'Send back',
  DOSSIER_BTN_ARCHIVE: 'Archive',
  DOSSIER_BTN_REOPEN: 'Reopen',
  DOSSIER_GOV_APPROVED: (date: string) => `Approved · ${date}`,
  DOSSIER_GOV_REVIEWED: (date: string) => `Reviewed · ${date}`,
  // Dossier — category fallbacks
  DOSSIER_CATEGORY_NOT_CLASSIFIED: 'Not classified',
  DOSSIER_CATEGORY_NOT_INFERRED: 'Archetype could not be inferred from this memo version.',
  // Dossier — placeholders
  DOSSIER_PLACEHOLDER_DEFAULT: 'Not available for this memo version',
  DOSSIER_CASHFLOW_PLACEHOLDER: 'Year-by-year cashflow not available for this memo version',
  DOSSIER_MITIGATION_PREFIX: 'Mitigation · ',
  // Dossier — table headers
  DOSSIER_TH_METRIC: 'Metric',
  DOSSIER_TH_VALUE: 'Value',
  DOSSIER_TH_CONF: 'Conf.',
  DOSSIER_TH_SOURCE: 'Source',
  DOSSIER_TH_TITLE: 'Title',
  DOSSIER_TH_SCENARIO: 'Scenario',
  DOSSIER_TH_DATE: 'Date',
  DOSSIER_TH_VERSION_COL: 'v',
  DOSSIER_TH_PROVIDER: 'Provider',
  DOSSIER_TH_CONFIDENCE: 'Confidence',
  DOSSIER_TH_STATUS: 'Status',
  // Dossier — confidence labels
  DOSSIER_CONF_HIGH: 'High conf.',
  DOSSIER_CONF_MED: 'Med conf.',
  DOSSIER_CONF_LOW: 'Low vis.',
  // Dossier — revenue model row keys
  DOSSIER_ROW_PRICING: 'Pricing',
  DOSSIER_ROW_CONTRACT: 'Contract structure',
  DOSSIER_ROW_ANCHOR: 'Anchor tenant',
  DOSSIER_ROW_RAMP: 'Ramp profile',
  // Dossier — generation metadata row keys
  DOSSIER_META_PROVIDER: 'Provider',
  DOSSIER_META_CONFIDENCE: 'Confidence',
  DOSSIER_META_STAKEHOLDER: 'Stakeholder',
  DOSSIER_META_AUDIENCE: 'Audience',
  DOSSIER_META_GEN_TIME: 'Generation time',
  DOSSIER_META_CREATED: 'Created',
  DOSSIER_META_DATA_AS_OF: 'Data as of',
  DOSSIER_META_SCENARIO: 'Scenario',

  // Financial
  FIN_PAGE_TITLE: '10-Year Financial Projection',
  FIN_SAVED_PLAN_LABEL: 'Saved plan',
  FIN_SAVED_PLAN_PLACEHOLDER: 'Select a saved scenario…',
  FIN_LOADING: 'Loading financial model…',
  FIN_EXCEL_SOON_TITLE: 'Excel export is not available yet',
  FIN_MEMO_DOSSIER_TITLE: "Open this scenario's strategic memo in the Dossier (PDF export available there)",

  // Financial — tabs
  FIN_TAB_TABLE: 'Table',
  FIN_TAB_CHARTS: 'Charts',
  FIN_TAB_DEBT: 'Debt Schedule',
  FIN_TAB_WATERFALL: 'Waterfall',
  FIN_TAB_SENSITIVITY: 'Sensitivity',

  // Financial — action buttons
  FIN_BTN_EXCEL_SOON: 'Excel (soon)',
  FIN_BTN_MEMO: 'Memo →',

  // Financial — KPI card labels
  FIN_KPI_TOTAL_CAPEX: 'Total CAPEX',
  FIN_KPI_PROJECT_IRR: 'IRR (Post-tax)',
  FIN_KPI_NPV: 'NPV (Post-tax)',
  FIN_KPI_MOIC: 'MOIC (Post-tax)',
  FIN_KPI_DSCR: 'DSCR (Stab.)',
  FIN_KPI_PAYBACK: 'Payback',
  FIN_KPI_TERMINAL: 'Terminal Value',
  FIN_KPI_STAB_REVENUE: 'Stab. Revenue',
  FIN_KPI_PER_YEAR: 'per year',
  FIN_KPI_SOURCE_SCORE: (score: number) => `Source score: ${score}/100`,

  // Financial — table headers
  FIN_TH_METRIC: 'Metric',
  FIN_TH_YEAR: (y: number) => `Year ${y}`,
  FIN_TH_YEAR_LABEL: 'Year',
  FIN_TH_OPENING_BALANCE: 'Opening Balance',
  FIN_TH_INTEREST: 'Interest',
  FIN_TH_PRINCIPAL: 'Principal',
  FIN_TH_CLOSING_BALANCE: 'Closing Balance',
  FIN_TH_TOTAL_SERVICE: 'Total Service',
  FIN_TH_DSCR: 'DSCR',

  // Financial — METRIC_COLS labels
  FIN_ROW_REVENUE: 'Revenue',
  FIN_ROW_POWER_COST: 'Power Cost',
  FIN_ROW_OPEX: 'OpEx',
  FIN_ROW_EBITDA: 'EBITDA',
  FIN_ROW_EBITDA_MARGIN: 'EBITDA Margin',
  FIN_ROW_DEBT_SERVICE: 'Debt Service',
  FIN_ROW_FREE_CASH_FLOW: 'Free Cash Flow',
  FIN_ROW_CUMULATIVE_FCF: 'Cumulative FCF',
  FIN_ROW_OCCUPANCY: 'Occupancy',

  // Financial — no-data states
  FIN_NODATA_PROJECTION: 'Projection Cannot Run',
  FIN_NODATA_PROJECTION_SUB: 'Configure and save a scenario in the',
  FIN_NODATA_PROJECTION_SUB2: 'to generate the 10-year financial model.',
  FIN_NODATA_DEBT: 'No Debt Configured',
  FIN_NODATA_DEBT_SUB: 'Set debt % and interest rate when saving a scenario in the',
  FIN_NODATA_EQUITY: 'No Equity Structure',
  FIN_NODATA_EQUITY_SUB: 'Set HEARST / Brookfield / Qatar equity % when saving a scenario in the',
  FIN_NODATA_SENSITIVITY: 'Could not compute sensitivity — check that both parameters are set in the base scenario.',

  // Financial — debt schedule KPI labels
  FIN_DEBT_PRINCIPAL: 'Principal',
  FIN_DEBT_TOTAL_INTEREST: 'Total Interest',
  FIN_DEBT_TERM: 'Term',
  FIN_DEBT_IO_PERIOD: 'IO Period',
  FIN_DEBT_MIN_DSCR: 'Min DSCR',
  FIN_DEBT_AVG_DSCR: 'Avg DSCR',
  FIN_DEBT_COVENANT_BREACHES: 'Covenant Breaches',
  FIN_DEBT_TERM_SUFFIX: ' yr',
  FIN_DEBT_NO_BREACH: 'None',

  // Financial — chart titles
  FIN_CHART_REVENUE_EBITDA: 'Revenue & EBITDA ($M)',
  FIN_CHART_CUMULATIVE_FCF: 'Cumulative Free Cash Flow ($M)',
  FIN_CHART_DEBT_BALANCE: 'Debt Balance Over Time ($M)',
  FIN_CHART_EQUITY_DIST: 'Equity Distributions by Investor ($M)',

  // Financial — sensitivity
  FIN_SENSITIVITY_TITLE: 'Sensitivity Matrix — IRR',
  FIN_SENSITIVITY_X_AXIS: 'X-Axis',
  FIN_SENSITIVITY_Y_AXIS: 'Y-Axis',
  FIN_LEGEND_NEGATIVE_IRR: '< 0% IRR',
  FIN_LEGEND_WEAK_IRR: '0–8%',
  FIN_LEGEND_BELOW_HURDLE: '8–15% (below IC hurdle)',
  FIN_LEGEND_ABOVE_HURDLE: '≥ 15% (IC hurdle)',
  FIN_LEGEND_BASELINE: 'Bold border = baseline scenario',

  // Financial — sensitivity param option labels
  FIN_PARAM_ELECTRICITY_PRICE: 'Electricity Price',
  FIN_PARAM_OCCUPANCY_PCT: 'Occupancy %',
  FIN_PARAM_RETAIL_PRICE: 'Retail Price',
  FIN_PARAM_WHOLESALE_PRICE: 'Wholesale Price',
  FIN_PARAM_HYPERSCALE_PRICE: 'Hyperscale Price',
  FIN_PARAM_IT_CAPACITY: 'IT Capacity (MW)',
  FIN_PARAM_DEBT_LEVERAGE: 'Debt Leverage',
  FIN_PARAM_EXIT_MULTIPLE: 'Exit Multiple',
  FIN_PARAM_PUE: 'PUE',

  // Financial — warnings
  FIN_WARNINGS_TITLE: 'INVESTMENT WARNINGS',

  // Errors
  ERR_GENERIC: 'Something went wrong. Please try again.',
  ERR_PROJECT_LOAD: 'Project load failed',
  ERR_PROJECT_TIMEOUT: 'Project load timed out — please refresh.',
  ERR_SAVE: 'Could not save',
  ERR_SAVE_DETAIL: (msg: string) => `Could not save: ${msg}`,
  ERR_DELETE: 'Delete failed',

  // Memo / advisor chrome
  MEMO_JOB_ARIA: 'Reopen the memo being generated',
  MEMO_JOB_TITLE: 'Memo in progress',
  MEMO_TOAST_DISMISS_ARIA: 'Dismiss notification',
  MEMO_COPY_TITLE: 'Copy markdown',
  MEMO_REGENERATE_TITLE: 'Regenerate',
  MEMO_DOWNLOAD_TITLE: 'Download .md',
  MEMO_CLOSE_TITLE: 'Close (job continues in background)',
  MEMO_GENERATING_LABEL: 'Generating strategic memo…',
  MEMO_SLA_WITHIN_TARGET: 'within target',
  MEMO_SLA_SLOWER: 'slower than usual',
  MEMO_STILL_WAITING_LLM: 'still waiting for the model',
  MEMO_JOB_WAITING_LLM: ' · still waiting',
  ADVISOR_RAIL_ARIA: 'ORACLE Investment Committee Advisor',

  // ── KPI education layer ────────────────────────────────────────────────────
  // Plain-English explanations for non-financial users. Three short lines each
  // (what it means · how ORACLE computes it · why it matters), ≤60 words, no
  // jargon. Surfaced by the subtle (i) InfoHint next to each metric.
  KPI_EDU_MEANS: 'What it means',
  KPI_EDU_HOW: 'How ORACLE calculates it',
  KPI_EDU_WHY: 'Why it matters',
  KPI_EDU_ARIA: (label: string) => `What is ${label}? Show explanation.`,
  KPI_EDU_ARIA_GENERIC: 'Show explanation',
  KPI_EDU: {
    irr: {
      means: 'The expected yearly return on the money you put in.',
      how: 'Worked out from the yearly cash the project generates plus what it sells for at exit.',
      why: 'A higher figure means each dollar invested earns more per year.',
    },
    moic: {
      means: 'How many times you get your money back in total.',
      how: 'Total cash returned — yearly cash plus the exit sale — divided by the money you put in.',
      why: 'A value of 2 means you end up with twice what you invested.',
    },
    npv: {
      means: 'The value created today, after accounting for the time you wait.',
      how: 'All future cash is discounted back to today and the money invested is subtracted.',
      why: 'A positive figure means the project is worth more than it costs.',
    },
    capex: {
      means: 'The upfront money needed to build the data center.',
      how: 'Adds up land, power, buildings, cooling and the computing hardware.',
      why: 'It is the cheque you write before any return comes back.',
    },
    terminal_value: {
      means: 'What the business is expected to be worth when you sell it.',
      how: 'The final-year earnings multiplied by a typical sale multiple for this kind of asset.',
      why: 'A large share of the return often depends on this exit price.',
    },
    payback: {
      means: 'How long until the project earns back the money you put in.',
      how: 'Counts the years until the cash received equals the upfront investment.',
      why: 'A shorter payback means your capital is at risk for less time.',
    },
    dscr: {
      means: 'Whether the project earns enough to cover its loan payments.',
      how: 'Yearly operating cash divided by the debt repayment due that year.',
      why: 'Below 1 means it cannot pay its debt; lenders watch this closely.',
    },
    returns_composition: {
      means: 'Where the equity value comes from — running the business versus selling it.',
      how: 'Compares the cash earned from operations against the proceeds from the final sale.',
      why: 'Heavy reliance on the sale means returns hinge on getting a good exit price.',
    },
    revenue: {
      means: 'The yearly sales the data center makes once it is full and running.',
      how: 'Capacity sold to customers multiplied by the going price for power and compute.',
      why: 'It is the top line every cost and profit is measured against.',
    },
    ebitda: {
      means: 'The yearly profit from running the business, before financing and tax.',
      how: 'Stabilised revenue minus the cost of operating the site.',
      why: 'It shows how much cash the operation itself throws off each year.',
    },
    source_score: {
      means: 'How well-backed the inputs behind this case are.',
      how: 'Rates each assumption on whether it is tied to a cited source or a placeholder.',
      why: 'A higher score means the numbers rest on evidence, not guesses.',
    },
    equity: {
      means: 'The cash you put in yourself, on top of any borrowed money.',
      how: 'Total build cost minus the part funded by debt, including interest during construction.',
      why: 'It is the capital actually at risk and the base your return is measured on.',
    },
    terminal_value_to_equity: {
      means: 'Your share of the sale price after the loan is repaid.',
      how: 'The expected sale value minus the debt still owed at exit.',
      why: 'It is the cash you actually pocket when the asset is sold.',
    },
    occupancy: {
      means: 'How full the data center is assumed to be.',
      how: 'The share of total capacity expected to be leased to paying customers.',
      why: 'Empty space earns nothing, so this drives revenue and the whole return.',
    },
    exit_year: {
      means: 'The year the model assumes you sell the asset.',
      how: 'Set by the scenario; the sale value is calculated for that year.',
      why: 'It fixes how long capital is tied up and when the final payout lands.',
    },
  },

  // Login (legacy layer — hors cockpit)
  LOGIN_PASSWORD_PLACEHOLDER: 'Password',
} as const;
