// @enable-adrien:layer=front-cockpit v=1
// ui-strings.ts — source de vérité pour les strings UI visibles par l'utilisateur.
// Importer UI.* dans les composants au lieu de strings en dur.
// Ajout de clés : additif uniquement (ne jamais réécrire une valeur existante).

export const UI = {
  // Navigation
  NAV_RAIL_ARIA: 'Hearst cockpit sections',
  NAV_SIMULATOR: 'Simulator',
  NAV_FINANCIAL: 'Financial',
  NAV_DEALS: 'Deals',
  NAV_WORKSPACE: 'Workspace',
  NAV_DOSSIER: 'Dossier',
  NAV_SOURCES: 'Sources',

  // Actions génériques
  ACTION_SAVE: 'Save',
  ACTION_DELETE: 'Delete',
  ACTION_CANCEL: 'Cancel',
  ACTION_RETRY: 'Retry',
  ACTION_CONFIRM: 'Confirm',
  ACTION_OPEN: 'Open',
  ACTION_EXPORT: 'Export',
  ACTION_GENERATE: 'Generate',

  // Assistant chat (FAB mobile)
  CHAT_OPEN: 'Open assistant',
  CHAT_CLOSE: 'Close assistant',

  // États
  STATE_LOADING: 'Loading…',
  STATE_SAVING: 'Saving…',
  STATE_CALCULATING: 'Calculating…',
  STATE_ERROR: 'An error occurred',

  // Simulator
  SIM_PAGE_EYEBROW: 'Oracle capital cockpit',
  SIM_PAGE_TITLE: 'Investment Simulator',
  SIM_PAGE_SUBTITLE: 'Shape a Qatar AI/data-center thesis from capital, operating model and GPU density.',
  SIM_BUILD_BRIEF_EYEBROW: 'Build brief',
  SIM_BUILD_BRIEF_TITLE: 'Set the investment constraint, then size the machine.',
  SIM_BUILD_BRIEF_HINT: 'Pick how the IC wants to think first: budget, power capacity, or target return. The simulator keeps the downstream scenario coherent.',
  SIM_PANEL_START_EYEBROW: 'Starting Point',
  SIM_PANEL_START_TITLE: 'Choose the control variable',
  SIM_PANEL_SIZE_EYEBROW: 'Project Size / Targets',
  SIM_PANEL_SIZE_TITLE: 'Calibrate the initial scenario',
  SIM_OS_EYEBROW: 'Operating thesis',
  SIM_OS_TITLE: 'Operating Model',
  SIM_OS_HINT: 'Choose one operating thesis',
  SIM_HW_EYEBROW: 'Technology stack',
  SIM_HW_TITLE: 'Hardware Allocation',
  SIM_HW_HINT: 'Power mix, rack density and GPU economics',
  SIM_READY_SCENARIOS: 'Ready scenarios',
  SIM_WHAT_TO_CHANGE: 'Solve by',
  SIM_INPUT_MODE_ARIA: 'Input mode',
  // Brief Bar — single control object (mode segments + driven field + computed results)
  SIM_QUICK_START: 'Quick start',
  SIM_QUICK_START_COUNT: (n: number) => `${n} templates`,
  SIM_MODE_BUDGET: 'Budget',
  SIM_MODE_SIZE: 'Size',
  SIM_MODE_RETURN: 'Target return',
  SIM_MODE_BUDGET_UNIT: '$',
  SIM_MODE_SIZE_UNIT: 'MW',
  SIM_MODE_RETURN_UNIT: '%',
  SIM_FIELD_BUDGET_LABEL: 'Money to invest',
  SIM_FIELD_SIZE_LABEL: 'Target capacity',
  SIM_FIELD_RETURN_LABEL: 'Yearly return target',
  SIM_FIELD_BUDGET_DESC: 'Total money to invest (USD). The engine estimates buildable capacity.',
  SIM_FIELD_SIZE_DESC: 'Target power capacity. Split into phases in advanced settings.',
  SIM_FIELD_RETURN_DESC: 'We work backwards on the lever you choose below.',
  SIM_FIELD_BUDGET_PLACEHOLDER: '500,000,000',
  SIM_FIELD_SIZE_PLACEHOLDER: '50',
  SIM_FIELD_RETURN_PLACEHOLDER: '18',
  SIM_AUTOFILL: 'Auto-fill with Qatar market data →',
  SIM_YOUR_CHOICE: 'Your choice',
  SIM_COMPUTED: 'Computed',
  SIM_RESULT_BUDGET: 'Budget',
  SIM_RESULT_SIZE: 'Size',
  SIM_RESULT_RETURN: 'Return',
  SIM_RESULT_PENDING: 'Run to compute',
  SIM_SOLVER_NO_SOLUTION: 'No solution — try a smaller target or another lever.',
  SIM_SOLVER_SOLVED: (n: number) => `Solved in ${n} steps`,
  SIM_LEVER_PRICING: 'Pricing',
  SIM_LEVER_CAPEX: 'Build cost',
  SIM_LEVER_LEVERAGE: 'Debt level',
  SIM_LEVER_MW: 'Size (MW)',
  // Operating Model cards — market proof per archetype (title/desc come from DEAL_ARCHETYPES)
  SIM_OS_SELECTED: 'Selected',
  SIM_OS_RECO: 'Reco',
  SIM_OS_M_POWERED_SHELL_ANCHOR: 'Equinix · Meta × Blue Owl',
  SIM_OS_M_POWERED_SHELL_PREVALENCE: '~80% of large-cap DC deals',
  SIM_OS_M_POWERED_SHELL_TAG: 'B2B',
  SIM_OS_M_NEOCLOUD_GPU_ANCHOR: 'CoreWeave · Lambda',
  SIM_OS_M_NEOCLOUD_GPU_PREVALENCE: 'Emerging (~25%)',
  SIM_OS_M_NEOCLOUD_GPU_TAG: 'B2B + B2C',
  SIM_OS_M_HYPERSCALER_ANCHOR: 'PIF × AWS',
  SIM_OS_M_HYPERSCALER_PREVALENCE: '~20% (minority LP)',
  SIM_OS_M_HYPERSCALER_TAG: 'B2B',
  SIM_OS_M_SOVEREIGN_AI_ANCHOR: 'G42 · HUMAIN',
  SIM_OS_M_SOVEREIGN_AI_PREVALENCE: 'Government-only',
  SIM_OS_M_SOVEREIGN_AI_TAG: 'B2B · gov',
  // Hardware Allocation — presets, tiers, KPIs, deployment readout, advanced controls
  HW_PRESET_COLO_NAME: 'Classic Colocation',
  HW_PRESET_COLO_TAGLINE: 'Mostly standard racks, little AI',
  HW_PRESET_MIXED_NAME: 'Mixed AI-Ready',
  HW_PRESET_MIXED_TAGLINE: 'Balanced colo + AI capacity',
  HW_PRESET_AI_NAME: 'AI Factory',
  HW_PRESET_AI_TAGLINE: 'GPU-dense, liquid-cooled',
  HW_TIER_STANDARD_NAME: 'Standard',
  HW_TIER_STANDARD_META: 'low power · ≤15 kW/rack',
  HW_TIER_DENSE_NAME: 'High-density',
  HW_TIER_DENSE_META: 'medium power · ≤60 kW/rack',
  HW_TIER_AI_NAME: 'AI clusters',
  HW_TIER_AI_META: 'very high power · ≥70 kW/rack',
  HW_KPI_CHIPS: 'AI chips',
  HW_KPI_RACKS: 'Racks',
  HW_KPI_EQUIP: 'Equipment cost',
  HW_KPI_REVENUE: 'AI revenue / yr',
  HW_DEPLOY_KICKER: 'Deployment',
  HW_DEPLOY_TITLE: (sku: string) => `${sku} map`,
  HW_AI_BADGE: (pct: number) => `${pct}% AI`,
  HW_READOUT_TOTAL: 'Total power',
  HW_READOUT_AI: 'AI fabric',
  HW_READOUT_RACKS: 'Racks implied',
  HW_MIX_STANDARD: 'Standard',
  HW_MIX_DENSE: 'Dense',
  HW_MIX_AI: 'AI',
  HW_ADV_SHOW: 'Tune GPU and power assumptions',
  HW_ADV_HIDE: 'Hide advanced controls',
  HW_ADV_POWER_TITLE: 'Power density per rack',
  HW_ADV_POWER_META: '(total 100%)',
  HW_ADV_AI_TITLE: 'AI chip',
  HW_ADV_AI_META: (mw: string) => `(${mw} MW dedicated)`,
  HW_ADV_UTILIZATION: 'Utilization',
  HW_ADV_PRICE: '$/hr',
  HW_POWER_HALL: 'Power hall',
  HW_AI_FABRIC: 'AI fabric',
  B2B_TH_CORNER: 'What we sell',
  HW_TOPOLOGY_ARIA: 'Hardware allocation topology',
  HW_GPU_UTIL_ARIA: 'AI chip utilization percentage',
  SIM_VALIDATE: 'Validate & see results →',
  SIM_SAVING: 'Saving…',
  SIM_SAVING_SCENARIO: 'Saving your scenario…',
  SIM_READY: 'Configuration ready.',
  SIM_FILL: 'Fill in your numbers to run the simulation.',
  SIM_FIX_ERROR: 'Fix the error above to continue.',
  SIM_PROJECT_UNAVAILABLE: 'Project unavailable — see error above.',
  SIM_LOADING_PROJECT: 'Resolving project…',
  RESULTS_LOADING_SCENARIO: 'Running scenario…',
  RESULTS_LOADING_ECOSYSTEM: 'Loading industry players…',
  RESULTS_LOADING_SANKEY: 'Loading money flow…',
  RESULTS_SCENARIO_SAVED: 'Scenario already saved',
  RESULTS_RISK_NOTE: 'Debt coverage sits below returns in the hierarchy.',
  RESULTS_CTA_FILL: 'Fill in your numbers to generate a plan',
  RESULTS_CTA_PLAN_READY: 'Plan ready',
  RESULTS_CTA_PLAN_REVIEW: 'Plan needs review',
  RESULTS_CTA_EXPORT: 'Export Summary',
  RESULTS_CTA_SAVE: 'Save Scenario',
  RESULTS_CTA_MEMO: 'Generate Strategic Memo',
  RESULTS_VERDICT_INSUFFICIENT: 'Insufficient data',
  RESULTS_VERDICT_NO_DATA: 'NO DATA',

  // Results (inline simulator + /results route)
  RESULTS_BACK_EDIT: '← Edit inputs',
  RESULTS_BM_CAPEX: 'Total CAPEX',
  RESULTS_BM_CAPEX_NOTE: 'Build requirement',
  RESULTS_BM_EBITDA: 'Stabilized EBITDA',
  RESULTS_BM_EBITDA_NOTE: 'Operating yield',
  RESULTS_BM_PAYBACK: 'Payback',
  RESULTS_BM_PAYBACK_NOTE: 'Capital recovery',
  RESULTS_BM_REVENUE: 'Stabilized revenue',
  RESULTS_BM_REVENUE_NOTE: 'Annual run-rate',
  RESULTS_BM_SOURCE: 'Source score',
  RESULTS_BM_SOURCE_NOTE: 'Evidence depth',
  RESULTS_BM_TERMINAL: 'Terminal value',
  RESULTS_BM_TERMINAL_NOTE: 'Exit valuation',
  RESULTS_CHIP_AI_SUFFIX: 'AI allocation',
  RESULTS_CHIP_NEEDS_REVIEW: (n: number) => `Needs review${n > 1 ? ` (${n})` : ''}`,
  RESULTS_DECISION_METRICS: 'Decision metrics',
  RESULTS_DM_IRR: 'IRR',
  RESULTS_DM_IRR_NOTE: 'annualized equity return',
  RESULTS_DM_MOIC: 'MOIC',
  RESULTS_DM_MOIC_NOTE: 'cash multiple at exit',
  RESULTS_DM_NPV: 'NPV',
  RESULTS_DM_NPV_NOTE: 'value created today',
  RESULTS_DONUT_LABEL: 'Capital',
  RESULTS_DONUT_VALUE: 'Stack',
  RESULTS_ECON_HINT: 'Scale, yield and evidence quality behind the return.',
  RESULTS_ECON_TITLE: 'Economics behind the decision',
  RESULTS_HERO_FALLBACK_NAME: 'Scenario Results',
  RESULTS_IM_BUILD_COST: 'Build cost',
  RESULTS_IM_DSCR: 'DSCR risk guardrail',
  RESULTS_IM_EQUITY_IDC: 'Equity (incl. IDC)',
  RESULTS_IM_EXIT_LABEL: 'Exit year',
  RESULTS_IM_EXIT_YEAR: (y: number) => `Year ${y}`,
  RESULTS_IM_IDC: 'Interest during construction',
  RESULTS_IM_IRR: 'IRR',
  RESULTS_IM_OCCUPANCY: 'Occupancy target',
  RESULTS_IM_TERMINAL: 'Terminal value',
  RESULTS_IM_TERMINAL_EQUITY: 'Terminal value (to equity)',
  RESULTS_LAYERS_HINT: 'Starting point, operating model and hardware allocation',
  RESULTS_LAYERS_TITLE: 'Scenario Layers',
  RESULTS_LAYER_HW: 'Hardware Allocation',
  RESULTS_LAYER_INDUSTRY: 'Industry Layer',
  RESULTS_LAYER_MODEL: 'Operating Model',
  RESULTS_LAYER_START: 'Starting Point',
  RESULTS_PROJ_EYEBROW: 'Main analysis',
  RESULTS_PROJ_HINT: '10-year cash generation, break-even path and exit value.',
  RESULTS_PROJ_TITLE: 'Financial Projection',
  RESULTS_RISK_GUARDRAIL: 'Risk guardrail',
  RESULTS_ROW_AI: 'AI exposure',
  RESULTS_ROW_BUSINESS: 'Business',
  RESULTS_ROW_CLIENT: 'Client',
  RESULTS_ROW_GPU: 'GPU SKU',
  RESULTS_ROW_MIX: 'Standard / dense / AI',
  RESULTS_ROW_MODE: 'Mode',
  RESULTS_ROW_MODEL: 'Model',
  RESULTS_ROW_POWER: 'Total power',
  RESULTS_ROW_PUE: 'PUE',
  RESULTS_ROW_REGION: 'Region',
  RESULTS_ROW_THESIS: 'Operating thesis',
  RESULTS_ROW_UTIL: 'Utilization',
  RESULTS_STACK_BROOKFIELD: 'Brookfield equity',
  RESULTS_STACK_DEBT: 'Debt',
  RESULTS_STACK_HEARST: 'HEARST equity',
  RESULTS_STACK_QATAR: 'Qatar equity',
  RESULTS_TIMELINE_HINT: 'Milestones and launch path',
  RESULTS_TIMELINE_TITLE: 'Deployment Timeline',
  RESULTS_VERDICT_INVESTMENT_GRADE: 'Investment-grade case',
  RESULTS_VERDICT_PENDING: 'Scenario pending',
  RESULTS_VERDICT_REWORK: 'Needs rework before IC',
  RESULTS_VERDICT_VIABLE: 'Viable, needs structuring',
  RESULTS_VIZ_HINT: 'Switch between strategic, industry and money-flow views',
  RESULTS_VIZ_MATRIX_DETAIL: 'Highlights which product layer and customer segment this scenario is really built for.',
  RESULTS_VIZ_MATRIX_LABEL: 'Industry layers',
  RESULTS_VIZ_MATRIX_TITLE: 'Commercial fit by product and buyer',
  RESULTS_VIZ_NETWORK_DETAIL: 'Shows the operators, hyperscalers, capital partners and local enablers around the scenario.',
  RESULTS_VIZ_NETWORK_LABEL: 'Industry players',
  RESULTS_VIZ_NETWORK_TITLE: 'Industry participant network',
  RESULTS_VIZ_RADAR_DETAIL: 'Compares brand control, bankability, speed, margin and exit liquidity.',
  RESULTS_VIZ_RADAR_LABEL: 'Strengths',
  RESULTS_VIZ_RADAR_TITLE: 'Operating-model strength map',
  RESULTS_VIZ_SANKEY_DETAIL: 'Traces equity, debt, build cost, revenue, operating costs and owner profit.',
  RESULTS_VIZ_SANKEY_LABEL: 'Money flow',
  RESULTS_VIZ_SANKEY_TITLE: 'Capital and annual cash-flow path',
  RESULTS_VIZ_TITLE: 'Visualizations',

  // Deals
  DEALS_NAV_ARIA: 'Deal models sections',
  DEALS_CALLOUT_SOVEREIGN: 'The sovereign rule',
  DEALS_CALLOUT_LOCAL: 'Implication for a local deal (a hub like Futur One)',
  DEALS_CLOSING_BOLD: 'The central reflex:',
  DEALS_CLOSING_BODY: 'value is not captured at the equity line alone. The operator keeps 20% but pockets recurring development + operations fees, and whoever holds land + power controls the bottleneck. Knowing which role you play determines what you negotiate.',

  // Workspace (scenarios only — reports → Dossier)
  WS_PAGE_SUBTITLE: 'Saved scenarios for this project. Reopen in the Simulator; strategic reports live in',
  WS_NO_SCENARIOS: 'No saved scenarios yet. Build one in the Simulator and click "Save this plan".',
  WS_NO_REPORTS: 'No reports yet. Generate a strategic memo from the Simulator.',
  WS_DELETE_CONFIRM: (name: string) => `Delete scenario "${name}"? This cannot be undone.`,

  // Sources
  SOURCES_LOADING: 'Loading market intelligence…',
  SOURCES_MY_SECTION: 'MY SOURCES — Admin & Project-specific',
  SOURCES_NO_DATA: 'No sources found.',
  SOURCES_NO_ADMIN: 'No admin sources yet.',
  SOURCES_NO_FILTER: 'No results matching filters.',
  SOURCES_ADD: 'Add source',
  SOURCES_DELETE_CONFIRM: 'Delete this source? This cannot be undone.',

  // Dossier
  DOSSIER_NO_REPORTS: 'No reports for this scenario yet. Generate a strategic memo from the',
  DOSSIER_NO_SCENARIO_REPORTS: 'No reports for this scenario yet.',
  DOSSIER_LOADING_MEMOS: 'Loading memos…',
  DOSSIER_NO_RISKS: 'No risks logged.',
  DOSSIER_NO_VERSIONS: 'No versions.',
  DOSSIER_GO_SIMULATOR: 'the Simulator',
  DOSSIER_EYEBROW_CONDITIONS: 'Conditions before approval',
  DOSSIER_EYEBROW_PEERS: "Why peers aren't directly comparable",
  DOSSIER_VERDICT_NOTE: 'Synthesized from return, risk, freshness & confidence signals',
  DOSSIER_PLACEHOLDER_STACK: 'Capital structure not available for this memo version',
  DOSSIER_PLACEHOLDER_TIMELINE: 'Deployment timeline not available for this memo version',
  DOSSIER_PLACEHOLDER_COMPARABLES: 'No comparable peers cited in this memo version',
  DOSSIER_PLACEHOLDER_RISKS: 'No risks logged for this memo version',
  DOSSIER_RISK_WHY: 'Why it matters ·',

  // Financial
  FIN_PAGE_TITLE: '10-Year Financial Projection',
  FIN_SAVED_PLAN_LABEL: 'Saved plan',
  FIN_SAVED_PLAN_PLACEHOLDER: 'Select a saved scenario…',
  FIN_LOADING: 'Loading financial model…',
  FIN_EXCEL_SOON_TITLE: 'Excel export is not available yet',
  FIN_MEMO_DOSSIER_TITLE: "Open this scenario's strategic memo in the Dossier (PDF export available there)",

  // Errors
  ERR_GENERIC: 'Something went wrong. Please try again.',
  ERR_PROJECT_LOAD: 'Project load failed',
  ERR_PROJECT_TIMEOUT: 'Project load timed out — please refresh.',
  ERR_SAVE: 'Could not save',
  ERR_SAVE_DETAIL: (msg: string) => `Could not save: ${msg}`,
  ERR_DELETE: 'Delete failed',

  // Memo / advisor chrome
  MEMO_JOB_ARIA: 'Reopen the memo being generated',
  MEMO_JOB_TITLE: 'Memo in progress',
  MEMO_TOAST_DISMISS_ARIA: 'Dismiss notification',
  MEMO_COPY_TITLE: 'Copy markdown',
  MEMO_REGENERATE_TITLE: 'Regenerate',
  MEMO_GENERATING_LABEL: 'Generating strategic memo…',
  ADVISOR_RAIL_ARIA: 'ORACLE Investment Committee Advisor',

  // Login (legacy layer — hors cockpit)
  LOGIN_PASSWORD_PLACEHOLDER: 'Password',
} as const;

export type UIKey = keyof typeof UI;
