-- Auto-generated seed
delete from crm.operators;
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('datacenter', 'LEAD', 'NTT GLOBAL DATA CENTERS', 'Japan · Global', 'HYPERSCALE PLATFORM', '1.5 GW operational across 20+ countries — the only Japanese-sovereign hyperscaler with full Middle East presence.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('datacenter', '#2', 'EDGECONNEX', 'USA · EQT-backed', 'DESIGN-BUILD VELOCITY', 'Hyperscale design-build specialist — sub-12-month campus delivery, 70+ markets globally.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('datacenter', '#3', 'COMPASS DATACENTERS', 'USA · Brookfield-backed', 'AI CAMPUS SPECIALIST', 'Purpose-built AI campuses for Microsoft, Meta, Oracle — single-tenant gigawatt scale.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('mining', 'LEAD', 'MARATHON DIGITAL — MARA', 'USA · Nasdaq: MARA', 'GLOBAL HASH LEADER', '50+ EH/s installed — the largest publicly listed Bitcoin miner globally, with active Abu Dhabi sovereign joint venture.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('mining', '#2', 'TERAWULF — WULF', 'USA · Nasdaq: WULF', 'CLEAN-ENERGY HPC', '95% zero-carbon energy mix — nuclear and hydro — with active pivot to AI/HPC hosting.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('mining', '#3', 'HUT 8 — HUT', 'Canada · Nasdaq: HUT', 'AI-NATIVE PIVOT', 'Most successful mining-to-AI pivot to date — Coatue & Bitmain partnerships, full HPC stack operational.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('hub', 'LEAD', 'EQUINIX', 'USA · Nasdaq: EQIX', 'INTERCONNECT BACKBONE', 'The global standard of interconnect — 260+ IBX data centers, 10,000+ enterprises, every major cloud on-net.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('hub', '#2', 'COREWEAVE', 'USA · NVIDIA-anchored', 'AI-CLOUD PARTNER', 'NVIDIA Partner of the Year — the AI-cloud benchmark for hyperscale GPU provisioning.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');
insert into crm.operators (pillar, rank, name, country, role, one_liner, status, notes) values ('hub', '#3', 'ALIGNED DATA CENTERS', 'USA · Macquarie-backed', 'AI-FACTORY HOSTING', 'Macquarie-backed AI-factory hosting — adaptive data center platform engineered for liquid-cooled GPU densities.', 'identified', 'Seed — initial target for Futur One × MISA pitch.');