'use client';

// StrategicMemoModal — Sprint 1 + Decision Canvas sprint.
//
// Full-screen drawer/modal that calls /api/admin/hearst/strategic-memo. While
// While the LLM runs it shows a live timeline. On success it no longer renders an
// 11-section accordion reader — it shows a decision-first SUCCESS STATE (verdict
// + 4 KPIs + category + actions) that routes straight to the Dossier Decision
// Canvas, where the full report and approval workflow live.
//
// No hex tokens — everything via var(--cp-*) / var(--ct-*).

import { useMemo, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { RotateCw, Copy, Download } from 'lucide-react';
import {
  useMemoJob,
  startMemoJob,
  hideMemoModal,
  formatElapsed,
} from '@/lib/hearst-memo-job-store';
import { deriveVerdict, deriveCategory, deriveKpis } from '@/lib/dossier-derive';
import { Modal, Button } from '@/components/hearst/ui';
import { UI } from '@/lib/ui-strings';
import { SLA_TARGET_MS, SLA_WARNING_MS, SLA_DANGER_MS } from '@/lib/constants';

/**
 * Live timeline shown during loading.
 *
 * We don't have SSE yet, so this shows real elapsed time and an SLA gauge.
 * The true model is revealed via meta.model_used when the memo arrives.
 */
function MemoTimeline({ elapsedMs, cascade }) {
  const pct = Math.min(100, (elapsedMs / SLA_DANGER_MS) * 100);
  const slaTone =
    elapsedMs < SLA_TARGET_MS ? 'normal' :
    elapsedMs < SLA_WARNING_MS ? 'warning' :
    'danger';
  const slaLabel =
    slaTone === 'normal' ? UI.MEMO_SLA_WITHIN_TARGET :
    slaTone === 'warning' ? UI.MEMO_SLA_SLOWER :
    UI.MEMO_STILL_WAITING_LLM;
  // Single sober accent — the latency state is conveyed by the text label, not colour.
  const slaColor = 'var(--cp-accent)';

  return (
    <div style={S.timelineWrap}>
      <div style={S.timelineHeader}>
        <span style={S.timelineSpinner} />
        <span style={S.timelineLabel}>{UI.MEMO_GENERATING_LABEL}</span>
        <span style={S.timelineElapsed}>{formatElapsed(elapsedMs)}</span>
      </div>

      <div style={S.slaWrap}>
        <div style={S.slaBar}>
          <div style={{ ...S.slaFill, width: `${pct}%`, background: slaColor }} />
          <div style={{ ...S.slaTarget, left: `${(SLA_TARGET_MS / SLA_DANGER_MS) * 100}%` }} />
        </div>
        <div style={{ ...S.slaLabel, color: slaColor }}>{slaLabel}</div>
      </div>

      <div style={S.cascadeWrap}>
        <div style={S.cascadeLabel}>Model :</div>
        <div style={S.cascadeList}>
          {cascade.map((model) => (
            <span key={model} style={S.cascadeChip}>{model}</span>
          ))}
        </div>
      </div>

      <div style={S.timelineHint}>
        You can close this window — the memo keeps generating in the background and
        you will be notified when it is ready.
      </div>
    </div>
  );
}

function toMarkdown(memo, meta) {
  if (!memo) return '';
  const lines = [];
  lines.push(`# Strategic Memo — ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');
  if (meta) {
    lines.push(`_Generated by ORACLE · stakeholder=${meta.oracle_ctx?.stakeholder} · region=${meta.oracle_ctx?.region} · model=${meta.model_used}_`);
    lines.push('');
  }
  if (memo.executive_summary) {
    lines.push('## Executive Summary');
    lines.push(`**${memo.executive_summary.headline || ''}**  · _${memo.executive_summary.overall_confidence || 'MED'} CONFIDENCE_`);
    for (const b of memo.executive_summary.bullets || []) lines.push(`- ${b}`);
    lines.push('');
  }
  const blocks = [
    ['Strategic Context', 'strategic_context', m => m.skip ? '_Not material._' : m.body],
    ['Key Financial Metrics', 'key_financial_metrics', m => (m.metrics || []).map(x => `- **${x.label}**: ${x.value ?? '—'}${x.unit ? ' ' + x.unit : ''}${x.confidence ? ` (${x.confidence})` : ''}${x.source ? ` · ${x.source}` : ''}`).join('\n') + `\n\n${m.narrative || ''}`],
    ['Infrastructure Analysis', 'infrastructure_analysis', m => `${m.body || ''}\n\n${(m.tradeoffs || []).map(x => `- ${x}`).join('\n')}`],
    ['Market Benchmarking', 'market_benchmarking', m => (m.comparables || []).map(c => `- **${c.name}** — ${c.metric} : ${c.value} _(${c.source})_`).join('\n')],
    ['Key Concerns', 'risks_constraints', m => (m.items || []).map(r => `- **[${r.severity}]** ${r.label} _(${r.category})_ — ${r.mitigation}`).join('\n')],
    ['Strategic Opportunities', 'strategic_opportunities', m => (m.items || []).map(o => `- **${o.label}** _(${o.confidence})_ — ${o.execution_path}`).join('\n')],
    ['Recommended Architecture', 'recommended_architecture', m => `${Object.entries(m.config || {}).map(([k, v]) => `- ${k} : ${v}`).join('\n')}\n\n${m.rationale || ''}`],
    ['Revenue Model', 'commercialization_strategy', m => `- Pricing : ${m.pricing ?? '—'}\n- Contract : ${m.contract_structure ?? '—'}\n- Anchor : ${m.anchor_tenant ?? '—'}\n- Ramp : ${m.ramp_profile ?? '—'}`],
    ['What Happens Next', 'deployment_roadmap', m => `${(m.phases || []).map(p => `- **${p.label}** (+${p.months_from_t0}) : ${(p.gating_events || []).join(', ')}`).join('\n')}\n\n${(m.reality_check_flags || []).map(f => `> ⚠ ${f}`).join('\n')}`],
    ['Long-Term Strategic Value', 'long_term_strategic_value', m => `${m.ten_year_arc || ''}\n\n${(m.speculative_branches || []).map(s => `- _(LOW VIS)_ ${s}`).join('\n')}`],
  ];
  for (const [title, key, fn] of blocks) {
    if (!memo[key]) continue;
    lines.push(`## ${title}`);
    lines.push(fn(memo[key]));
    lines.push('');
  }
  return lines.join('\n');
}

// ─── Decision-first success state (replaces the accordion reader) ────────────

function SuccessState({ memo, meta, title, router }) {
  const verdict = deriveVerdict(memo);
  const category = deriveCategory(memo);
  const kpis = deriveKpis(memo).slice(0, 4);
  const persisted = meta?.persisted || null;
  const memoId = persisted?.id || null;
  const status = persisted?.status || 'draft';

  function viewCanvas() {
    if (!memoId) return;
    hideMemoModal();
    router.push(`/admin/hearst/dossier?memo=${memoId}`);
  }

  return (
    <div style={S.success}>
      <div style={S.successBanner}>
        <span style={S.successText}>Report created</span>
        <span style={S.statusText}>{status}</span>
      </div>

      {title && <h3 style={S.successTitle}>{memo.executive_summary?.headline || title}</h3>}

      <div style={S.successVerdictRow}>
        <span style={S.verdictBadge}>{verdict.label}</span>
        {category && <span style={S.categoryText}>{category}</span>}
        {verdict.drivers?.length > 0 && <span style={S.driversText}>{verdict.drivers.join(' · ')}</span>}
      </div>

      <div style={S.successKpis}>
        {kpis.map(k => (
          <div key={k.key} style={S.successKpi}>
            <div style={S.successKpiLabel}>{k.label}</div>
            <div style={S.successKpiValue}>{k.value || '—'}</div>
            {k.sub && <div style={S.successKpiSub}>{k.sub}</div>}
          </div>
        ))}
      </div>

      <div style={S.successActions}>
        <Button variant="primary" size="md" type="button" onClick={viewCanvas} disabled={!memoId}>
          View Decision Canvas →
        </Button>
        {memoId ? (
          <Button
            variant="secondary"
            size="md"
            href={`/api/admin/hearst/strategic-memos/${memoId}/pdf`}
            target="_blank"
            rel="noreferrer"
          >
            Export PDF
          </Button>
        ) : (
          <Button variant="secondary" size="md" type="button" disabled>
            Export PDF
          </Button>
        )}
        <Button variant="secondary" size="md" type="button" onClick={viewCanvas} disabled={!memoId}>
          Review / Approve
        </Button>
      </div>

      <div style={S.successNote}>
        {memoId
          ? 'Saved to the Dossier — versioned and retained automatically. Review and approval happen on the Decision Canvas.'
          : 'Generated but not yet persisted — retry or download below; the Decision Canvas opens once the report is saved.'}
      </div>
    </div>
  );
}

/**
 * StrategicMemoModal — view layer over the global memo-job store
 * (lib/hearst-memo-job-store.js). The job survives the modal unmounting; a
 * bottom-right badge + toast take over the visual relay.
 */
export default function StrategicMemoModal() {
  const job = useMemoJob();
  const router = useRouter();
  const open    = job.modal_visible;
  const loading = job.status === 'loading';
  const error   = job.status === 'error' ? job.error : null;
  const memo    = job.result?.memo || null;
  const meta    = job.result?.meta || null;
  const title   = job.request?.title || 'Strategic Memo';

  const refetch = useCallback(() => {
    if (job.request) startMemoJob(job.request);
  }, [job.request]);

  // Focus trap handled by <Modal> (useFocusTrap).

  const md = useMemo(() => toMarkdown(memo, meta), [memo, meta]);

  function downloadMd() {
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `strategic-memo-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }
  function copyMd() {
    if (navigator?.clipboard?.writeText) navigator.clipboard.writeText(md);
  }

  if (!open) return null;

  return (
    <Modal
      isOpen={true}
      onClose={hideMemoModal}
      title={
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <span>{title}</span>
          {meta && (
            <div style={S.meta}>
              <span>{meta.oracle_ctx?.stakeholder} · {meta.oracle_ctx?.region}</span>
              <span> · {meta.model_used}</span>
              {meta.generated_at && <span> · {new Date(meta.generated_at).toLocaleString()}</span>}
            </div>
          )}
        </div>
      }
      footer={
        <div style={S.actions}>
          <button type="button" onClick={refetch} disabled={loading} style={S.actionBtn} title={UI.MEMO_REGENERATE_TITLE} aria-label={UI.MEMO_REGENERATE_TITLE}><RotateCw size={15} aria-hidden="true" /></button>
          <button type="button" onClick={copyMd} disabled={!memo} style={S.actionBtn} title={UI.MEMO_COPY_TITLE} aria-label={UI.MEMO_COPY_TITLE}><Copy size={15} aria-hidden="true" /></button>
          <button type="button" onClick={downloadMd} disabled={!memo} style={S.actionBtn} title={UI.MEMO_DOWNLOAD_TITLE} aria-label={UI.MEMO_DOWNLOAD_TITLE}><Download size={15} aria-hidden="true" /></button>
        </div>
      }
    >
      {loading && <MemoTimeline elapsedMs={job.elapsed_ms} cascade={job.cascade} />}
      {error && <div style={S.error}>Error : {error}</div>}
      {memo && <SuccessState memo={memo} meta={meta} title={title} router={router} />}
    </Modal>
  );
}

const S = {
  meta: { fontSize: 'var(--cp-font-micro)', color: 'var(--cp-text-muted)', marginTop: 'var(--cp-space-1)', fontFamily: 'ui-monospace, monospace' },

  actions: { display: 'flex', gap: 'var(--cp-space-2)' },
  actionBtn: { width: 'var(--cp-icon-btn-size)', height: 'var(--cp-icon-btn-size)', padding: 0, background: 'var(--cp-surface-2)', color: 'var(--cp-text-primary)', border: '1px solid var(--cp-border)', borderRadius: 'var(--cp-radius-sm)', cursor: 'pointer', fontSize: 'var(--cp-font-md)' },

  // Timeline (loading)
  timelineWrap: { padding: 'var(--cp-space-6) var(--cp-space-5)', background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)', borderRadius: 'var(--cp-radius-md)', display: 'flex', flexDirection: 'column', gap: 'var(--cp-space-4)' },
  timelineHeader: { display: 'flex', alignItems: 'center', gap: 'var(--cp-space-3)', fontSize: 'var(--cp-font-base)', fontWeight: 'var(--cp-weight-bold)', color: 'var(--cp-text-primary)' },
  timelineSpinner: { display: 'inline-block', width: 'var(--cp-spinner-size)', height: 'var(--cp-spinner-size)', borderRadius: '50%', border: 'var(--cp-border-w-accent) solid var(--cp-border)', borderTopColor: 'var(--cp-accent-maroon, var(--cp-accent))', animation: 'memo-spin 0.9s linear infinite' },
  timelineLabel: { flex: 1 },
  timelineElapsed: { fontFamily: 'ui-monospace, monospace', fontSize: 'var(--cp-font-sm)', fontWeight: 'var(--cp-weight-black)', color: 'var(--cp-text-strong)', fontVariantNumeric: 'tabular-nums' },
  slaWrap: { display: 'flex', flexDirection: 'column', gap: 'var(--cp-space-1)' },
  slaBar: { position: 'relative', height: 6, background: 'var(--cp-surface-0)', borderRadius: 'var(--cp-radius-pill)', overflow: 'hidden' },
  slaFill: { position: 'absolute', inset: 0, right: 'auto', height: '100%', borderRadius: 'var(--cp-radius-pill)', transition: 'width 1s linear, background var(--cp-dur-base) var(--cp-ease)' },
  slaTarget: { position: 'absolute', top: -2, height: 10, width: 2, background: 'var(--cp-border-strong)' },
  slaLabel: { fontSize: 'var(--cp-font-micro)', fontWeight: 'var(--cp-weight-bold)', textTransform: 'uppercase', letterSpacing: 'var(--cp-tracking-wider)' },
  cascadeWrap: { display: 'flex', flexDirection: 'column', gap: 'var(--cp-space-2)' },
  cascadeLabel: { fontSize: 'var(--cp-font-micro)', fontWeight: 'var(--cp-weight-bold)', color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 'var(--cp-tracking-wider)' },
  cascadeList: { display: 'flex', gap: 'var(--cp-space-2)', flexWrap: 'wrap' },
  cascadeChip: { display: 'inline-flex', alignItems: 'center', padding: 'var(--cp-space-1) var(--cp-space-2)', background: 'var(--cp-surface-0)', color: 'var(--cp-text-muted)', border: '1px solid var(--cp-border)', borderRadius: 'var(--cp-radius-pill)', fontSize: 'var(--cp-font-micro)', fontFamily: 'ui-monospace, monospace', letterSpacing: 'var(--cp-tracking-wide)' },
  timelineHint: { fontSize: 'var(--cp-font-xs)', color: 'var(--cp-text-muted)', fontStyle: 'italic', lineHeight: 'var(--cp-leading-body)', paddingTop: 'var(--cp-space-2)', borderTop: '1px dashed var(--cp-border)' },

  error: { padding: 'var(--cp-space-4)', background: 'var(--cp-error-bg)', color: 'var(--cp-error)', border: '1px solid var(--cp-border)', borderRadius: 'var(--cp-radius-md)', fontSize: 'var(--cp-font-sm)', fontWeight: 'var(--cp-weight-semibold)' },

  // Success state (sober — no status colours, no badges)
  success: { display: 'flex', flexDirection: 'column', gap: 'var(--cp-space-4)' },
  successBanner: { display: 'flex', alignItems: 'center', gap: 'var(--cp-space-3)' },
  successText: { fontSize: 'var(--cp-font-md)', fontWeight: 'var(--cp-weight-black)', color: 'var(--cp-text-primary)', textTransform: 'uppercase', letterSpacing: 'var(--cp-tracking-wider)', flex: 1 },
  statusText: { fontSize: 'var(--cp-font-xs)', color: 'var(--cp-text-muted)', textTransform: 'capitalize', fontWeight: 'var(--cp-weight-semibold)' },
  successTitle: { fontSize: 'var(--cp-font-lg)', fontWeight: 'var(--cp-weight-bold)', color: 'var(--cp-text-primary)', lineHeight: 'var(--cp-leading-tight)', margin: 0 },

  successVerdictRow: { display: 'flex', alignItems: 'center', gap: 'var(--cp-space-3)', flexWrap: 'wrap' },
  verdictBadge: { fontSize: 'var(--cp-font-xl)', fontWeight: 'var(--cp-weight-black)', letterSpacing: 'var(--cp-tracking-wider)', color: 'var(--cp-text-primary)', textTransform: 'uppercase', lineHeight: 'var(--cp-leading-heading)', paddingLeft: 'var(--cp-space-3)', borderLeft: 'var(--cp-border-w-bar) solid var(--cp-accent)' },
  categoryText: { fontSize: 'var(--cp-font-base)', fontWeight: 'var(--cp-weight-black)', color: 'var(--cp-text-primary)' },
  driversText: { fontSize: 'var(--cp-font-sm)', color: 'var(--cp-text-muted)' },

  successKpis: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: 'var(--cp-space-3)' },
  successKpi: { padding: 'var(--cp-space-3) var(--cp-space-4)', borderRadius: 'var(--cp-radius-md)', background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)' },
  successKpiLabel: { fontSize: 'var(--cp-font-micro)', fontWeight: 'var(--cp-weight-black)', color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 'var(--cp-tracking-eyebrow)' },
  successKpiValue: { fontSize: 'var(--cp-font-xl)', fontWeight: 'var(--cp-weight-black)', color: 'var(--cp-text-primary)', lineHeight: 'var(--cp-leading-snug)', marginTop: 'var(--cp-space-1)', fontVariantNumeric: 'tabular-nums' },
  successKpiSub: { fontSize: 'var(--cp-font-micro)', color: 'var(--cp-text-muted)', marginTop: 'var(--cp-space-1)' },

  successActions: { display: 'flex', gap: 'var(--cp-space-3)', flexWrap: 'wrap' },
  successNote: { fontSize: 'var(--cp-font-sm)', color: 'var(--cp-text-muted)', lineHeight: 'var(--cp-leading-body)', paddingTop: 'var(--cp-space-3)', borderTop: '1px dashed var(--cp-border)', fontStyle: 'italic' },
};
