'use client';

// StrategicMemoModal — Sprint 1 + Decision Canvas sprint.
//
// Full-screen drawer/modal that calls /api/admin/hearst/strategic-memo. While
// the cascade runs it shows a live timeline. On success it no longer renders an
// 11-section accordion reader — it shows a decision-first SUCCESS STATE (verdict
// + 4 KPIs + category + actions) that routes straight to the Dossier Decision
// Canvas, where the full report and approval workflow live.
//
// No hex tokens — everything via var(--cp-*) / var(--ct-*).

import { useEffect, useMemo, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import {
  useMemoJob,
  startMemoJob,
  hideMemoModal,
  formatElapsed,
} from '@/lib/hearst-memo-job-store';
import { deriveVerdict, deriveCategory, deriveKpis } from '@/lib/dossier-derive';

/**
 * Live timeline shown during loading.
 *
 * We can't know server-side cascade position from the client (no SSE yet), so we
 * show: real elapsed time, an SLA gauge vs the 60s target, and the full fallback
 * chain enumerated without faking an "active" stage. The true model is revealed
 * via meta.model_used when the memo arrives.
 */
const SLA_TARGET_MS = 60_000;
const SLA_WARNING_MS = 120_000;
const SLA_DANGER_MS = 240_000;

function MemoTimeline({ elapsedMs, cascade }) {
  const pct = Math.min(100, (elapsedMs / SLA_DANGER_MS) * 100);
  const slaTone =
    elapsedMs < SLA_TARGET_MS ? 'normal' :
    elapsedMs < SLA_WARNING_MS ? 'warning' :
    'danger';
  const slaLabel =
    slaTone === 'normal' ? 'within target' :
    slaTone === 'warning' ? 'slower than usual' :
    'cascade fallback in progress';
  // Single sober accent — the latency state is conveyed by the text label, not colour.
  const slaColor = 'var(--cp-accent)';

  return (
    <div style={S.timelineWrap}>
      <div style={S.timelineHeader}>
        <span style={S.timelineSpinner} />
        <span style={S.timelineLabel}>Generating strategic memo…</span>
        <span style={S.timelineElapsed}>{formatElapsed(elapsedMs)}</span>
      </div>

      <div style={S.slaWrap}>
        <div style={S.slaBar}>
          <div style={{ ...S.slaFill, width: `${pct}%`, background: slaColor }} />
          <div style={{ ...S.slaTarget, left: `${(SLA_TARGET_MS / SLA_DANGER_MS) * 100}%` }} />
        </div>
        <div style={{ ...S.slaLabel, color: slaColor }}>{slaLabel}</div>
      </div>

      <div style={S.cascadeWrap}>
        <div style={S.cascadeLabel}>Fallback chain :</div>
        <div style={S.cascadeList}>
          {cascade.map((model) => (
            <span key={model} style={S.cascadeChip}>{model}</span>
          ))}
          <span style={{ ...S.cascadeChip, ...S.cascadeChipFallback }}>claude-sonnet-4-6</span>
          <span style={{ ...S.cascadeChip, ...S.cascadeChipFallback }}>gpt-4o</span>
        </div>
      </div>

      <div style={S.timelineHint}>
        You can close this window — the memo keeps generating in the background and
        you will be notified when it is ready.
      </div>
    </div>
  );
}

function toMarkdown(memo, meta) {
  if (!memo) return '';
  const lines = [];
  lines.push(`# Strategic Memo — ${new Date().toISOString().slice(0, 10)}`);
  lines.push('');
  if (meta) {
    lines.push(`_Generated by ORACLE · stakeholder=${meta.oracle_ctx?.stakeholder} · region=${meta.oracle_ctx?.region} · model=${meta.model_used}_`);
    lines.push('');
  }
  if (memo.executive_summary) {
    lines.push('## Executive Summary');
    lines.push(`**${memo.executive_summary.headline || ''}**  · _${memo.executive_summary.overall_confidence || 'MED'} CONFIDENCE_`);
    for (const b of memo.executive_summary.bullets || []) lines.push(`- ${b}`);
    lines.push('');
  }
  const blocks = [
    ['Strategic Context', 'strategic_context', m => m.skip ? '_Not material._' : m.body],
    ['Key Financial Metrics', 'key_financial_metrics', m => (m.metrics || []).map(x => `- **${x.label}**: ${x.value ?? '—'}${x.unit ? ' ' + x.unit : ''}${x.confidence ? ` (${x.confidence})` : ''}${x.source ? ` · ${x.source}` : ''}`).join('\n') + `\n\n${m.narrative || ''}`],
    ['Infrastructure Analysis', 'infrastructure_analysis', m => `${m.body || ''}\n\n${(m.tradeoffs || []).map(x => `- ${x}`).join('\n')}`],
    ['Market Benchmarking', 'market_benchmarking', m => (m.comparables || []).map(c => `- **${c.name}** — ${c.metric} : ${c.value} _(${c.source})_`).join('\n')],
    ['Risks & Constraints', 'risks_constraints', m => (m.items || []).map(r => `- **[${r.severity}]** ${r.label} _(${r.category})_ — ${r.mitigation}`).join('\n')],
    ['Strategic Opportunities', 'strategic_opportunities', m => (m.items || []).map(o => `- **${o.label}** _(${o.confidence})_ — ${o.execution_path}`).join('\n')],
    ['Recommended Architecture', 'recommended_architecture', m => `${Object.entries(m.config || {}).map(([k, v]) => `- ${k} : ${v}`).join('\n')}\n\n${m.rationale || ''}`],
    ['Commercialization Strategy', 'commercialization_strategy', m => `- Pricing : ${m.pricing ?? '—'}\n- Contract : ${m.contract_structure ?? '—'}\n- Anchor : ${m.anchor_tenant ?? '—'}\n- Ramp : ${m.ramp_profile ?? '—'}`],
    ['Deployment Roadmap', 'deployment_roadmap', m => `${(m.phases || []).map(p => `- **${p.label}** (+${p.months_from_t0}) : ${(p.gating_events || []).join(', ')}`).join('\n')}\n\n${(m.reality_check_flags || []).map(f => `> ⚠ ${f}`).join('\n')}`],
    ['Long-Term Strategic Value', 'long_term_strategic_value', m => `${m.ten_year_arc || ''}\n\n${(m.speculative_branches || []).map(s => `- _(LOW VIS)_ ${s}`).join('\n')}`],
  ];
  for (const [title, key, fn] of blocks) {
    if (!memo[key]) continue;
    lines.push(`## ${title}`);
    lines.push(fn(memo[key]));
    lines.push('');
  }
  return lines.join('\n');
}

// ─── Decision-first success state (replaces the accordion reader) ────────────

function SuccessState({ memo, meta, title, router }) {
  const verdict = deriveVerdict(memo);
  const category = deriveCategory(memo);
  const kpis = deriveKpis(memo).slice(0, 4);
  const persisted = meta?.persisted || null;
  const memoId = persisted?.id || null;
  const status = persisted?.status || 'draft';

  function viewCanvas() {
    if (!memoId) return;
    hideMemoModal();
    router.push(`/admin/hearst/dossier?memo=${memoId}`);
  }

  return (
    <div style={S.success}>
      <div style={S.successBanner}>
        <span style={S.successText}>Report created</span>
        <span style={S.statusText}>{status}</span>
      </div>

      {title && <h3 style={S.successTitle}>{memo.executive_summary?.headline || title}</h3>}

      <div style={S.successVerdictRow}>
        <span style={S.verdictBadge}>{verdict.label}</span>
        {category && <span style={S.categoryText}>{category}</span>}
        {verdict.drivers?.length > 0 && <span style={S.driversText}>{verdict.drivers.join(' · ')}</span>}
      </div>

      <div style={S.successKpis}>
        {kpis.map(k => (
          <div key={k.key} style={S.successKpi}>
            <div style={S.successKpiLabel}>{k.label}</div>
            <div style={S.successKpiValue}>{k.value || '—'}</div>
            {k.sub && <div style={S.successKpiSub}>{k.sub}</div>}
          </div>
        ))}
      </div>

      <div style={S.successActions}>
        <button type="button" onClick={viewCanvas} disabled={!memoId} style={S.ctaPrimary}>
          View Decision Canvas →
        </button>
        {memoId ? (
          <a style={S.ctaSecondary} href={`/api/admin/hearst/strategic-memos/${memoId}/pdf`} target="_blank" rel="noreferrer">
            Export PDF
          </a>
        ) : (
          <button type="button" onClick={() => {}} disabled style={S.ctaSecondary}>Export PDF</button>
        )}
        <button type="button" onClick={viewCanvas} disabled={!memoId} style={S.ctaSecondary}>
          Review / Approve
        </button>
      </div>

      <div style={S.successNote}>
        {memoId
          ? 'Saved to the Dossier — versioned and retained automatically. Review and approval happen on the Decision Canvas.'
          : 'Generated but not yet persisted — retry or download below; the Decision Canvas opens once the report is saved.'}
      </div>
    </div>
  );
}

/**
 * StrategicMemoModal — view layer over the global memo-job store
 * (lib/hearst-memo-job-store.js). The job survives the modal unmounting; a
 * bottom-right badge + toast take over the visual relay.
 */
export default function StrategicMemoModal(_legacyProps) {
  const job = useMemoJob();
  const router = useRouter();
  const open    = job.modal_visible;
  const loading = job.status === 'loading';
  const error   = job.status === 'error' ? job.error : null;
  const memo    = job.result?.memo || null;
  const meta    = job.result?.meta || null;
  const title   = job.request?.title || 'Strategic Memo';

  const refetch = useCallback(() => {
    if (job.request) startMemoJob(job.request);
  }, [job.request]);

  useEffect(() => {
    if (!open) return;
    function onKey(e) { if (e.key === 'Escape') hideMemoModal(); }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open]);

  const md = useMemo(() => toMarkdown(memo, meta), [memo, meta]);

  function downloadMd() {
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `strategic-memo-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }
  function copyMd() {
    if (navigator?.clipboard?.writeText) navigator.clipboard.writeText(md);
  }

  if (!open) return null;

  return (
    <div style={S.backdrop} role="dialog" aria-label={title} onClick={hideMemoModal}>
      <div style={S.modal} onClick={e => e.stopPropagation()}>
        <header style={S.head}>
          <div>
            <h2 style={S.title}>{title}</h2>
            {meta && (
              <div style={S.meta}>
                <span>{meta.oracle_ctx?.stakeholder} · {meta.oracle_ctx?.region}</span>
                <span> · {meta.model_used}</span>
                {meta.generated_at && <span> · {new Date(meta.generated_at).toLocaleString()}</span>}
              </div>
            )}
          </div>
          <div style={S.actions}>
            <button type="button" onClick={refetch} disabled={loading} style={S.actionBtn} title="Regenerate">↻</button>
            <button type="button" onClick={copyMd} disabled={!memo} style={S.actionBtn} title="Copy markdown">⧉</button>
            <button type="button" onClick={downloadMd} disabled={!memo} style={S.actionBtn} title="Download .md">↓</button>
            <button type="button" onClick={hideMemoModal} style={S.closeBtn} aria-label="Close (job continues in background)">×</button>
          </div>
        </header>

        <div style={S.body}>
          {loading && <MemoTimeline elapsedMs={job.elapsed_ms} cascade={job.cascade} />}
          {error && <div style={S.error}>Error : {error}</div>}
          {memo && <SuccessState memo={memo} meta={meta} title={title} router={router} />}
        </div>
      </div>
    </div>
  );
}

const S = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1010,
    background: 'rgba(0, 0, 0, 0.72)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 16px',
  },
  modal: {
    width: '100%',
    maxWidth: 720,
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    background: 'linear-gradient(var(--cp-surface-2), var(--cp-surface-2)), var(--cp-bg-deep)',
    border: '1px solid var(--cp-border-strong, var(--cp-border))',
    borderRadius: 'var(--cp-radius-lg)',
    overflow: 'hidden',
    boxShadow: 'var(--cp-shadow-lg), 0 0 0 1px rgba(255, 255, 255, 0.06) inset',
  },

  head: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16, padding: '16px 20px', borderBottom: '1px solid var(--cp-border)' },
  title: { fontSize: 16, fontWeight: 800, color: 'var(--cp-text-primary)', margin: 0, letterSpacing: 0.3 },
  meta: { fontSize: 10, color: 'var(--cp-text-muted)', marginTop: 4, fontFamily: 'ui-monospace, monospace' },

  actions: { display: 'flex', gap: 6 },
  actionBtn: { width: 32, height: 32, padding: 0, background: 'var(--cp-surface-2)', color: 'var(--cp-text-primary)', border: '1px solid var(--cp-border)', borderRadius: 8, cursor: 'pointer', fontSize: 14 },
  closeBtn: { width: 32, height: 32, padding: 0, background: 'transparent', color: 'var(--cp-text-muted)', border: 'none', cursor: 'pointer', fontSize: 18, lineHeight: 1 },

  body: { padding: 20, overflowY: 'auto', flex: 1 },

  // Timeline (loading)
  timelineWrap: { padding: '24px 20px', background: 'var(--cp-surface-2)', border: '1px solid var(--cp-border)', borderRadius: 12, display: 'flex', flexDirection: 'column', gap: 16 },
  timelineHeader: { display: 'flex', alignItems: 'center', gap: 12, fontSize: 13, fontWeight: 700, color: 'var(--cp-text-primary)' },
  timelineSpinner: { display: 'inline-block', width: 14, height: 14, borderRadius: '50%', border: '2px solid var(--cp-border)', borderTopColor: 'var(--cp-accent-maroon, var(--cp-accent))', animation: 'memo-spin 0.9s linear infinite' },
  timelineLabel: { flex: 1 },
  timelineElapsed: { fontFamily: 'ui-monospace, monospace', fontSize: 12, fontWeight: 800, color: 'var(--cp-text-strong)', fontVariantNumeric: 'tabular-nums' },
  slaWrap: { display: 'flex', flexDirection: 'column', gap: 4 },
  slaBar: { position: 'relative', height: 6, background: 'var(--cp-surface-0)', borderRadius: 999, overflow: 'hidden' },
  slaFill: { position: 'absolute', inset: 0, right: 'auto', height: '100%', borderRadius: 999, transition: 'width 1s linear, background 300ms ease' },
  slaTarget: { position: 'absolute', top: -2, height: 10, width: 2, background: 'var(--cp-border-strong)' },
  slaLabel: { fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0.5 },
  cascadeWrap: { display: 'flex', flexDirection: 'column', gap: 6 },
  cascadeLabel: { fontSize: 10, fontWeight: 700, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.5 },
  cascadeList: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  cascadeChip: { display: 'inline-flex', alignItems: 'center', padding: '3px 8px', background: 'var(--cp-surface-0)', color: 'var(--cp-text-muted)', border: '1px solid var(--cp-border)', borderRadius: 999, fontSize: 10, fontFamily: 'ui-monospace, monospace', letterSpacing: 0.2 },
  cascadeChipFallback: { background: 'var(--cp-accent-soft, var(--cp-surface-0))', color: 'var(--cp-accent)', borderColor: 'var(--cp-border-accent, var(--cp-border))' },
  timelineHint: { fontSize: 11, color: 'var(--cp-text-muted)', fontStyle: 'italic', lineHeight: 1.5, paddingTop: 8, borderTop: '1px dashed var(--cp-border)' },

  error: { padding: 16, background: 'var(--cp-error-bg)', color: 'var(--cp-error)', border: '1px solid var(--cp-border)', borderRadius: 10, fontSize: 12, fontWeight: 600 },

  // Success state (sober — no status colours, no badges)
  success: { display: 'flex', flexDirection: 'column', gap: 16 },
  successBanner: { display: 'flex', alignItems: 'center', gap: 10 },
  successText: { fontSize: 14, fontWeight: 800, color: 'var(--cp-text-primary)', textTransform: 'uppercase', letterSpacing: 0.5, flex: 1 },
  statusText: { fontSize: 11, color: 'var(--cp-text-muted)', textTransform: 'capitalize', fontWeight: 600 },
  successTitle: { fontSize: 17, fontWeight: 700, color: 'var(--cp-text-primary)', lineHeight: 1.35, margin: 0 },

  successVerdictRow: { display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  verdictBadge: { fontSize: 'var(--cp-font-xl)', fontWeight: 800, letterSpacing: 0.5, color: 'var(--cp-text-primary)', textTransform: 'uppercase', lineHeight: 1.2, paddingLeft: 12, borderLeft: '3px solid var(--cp-accent)' },
  categoryText: { fontSize: 13, fontWeight: 800, color: 'var(--cp-text-primary)' },
  driversText: { fontSize: 12, color: 'var(--cp-text-muted)' },

  successKpis: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(120px, 1fr))', gap: 10 },
  successKpi: { padding: '12px 14px', borderRadius: 10, background: 'var(--cp-surface-0)', border: '1px solid var(--cp-border)' },
  successKpiLabel: { fontSize: 10, fontWeight: 800, color: 'var(--cp-text-muted)', textTransform: 'uppercase', letterSpacing: 0.6 },
  successKpiValue: { fontSize: 22, fontWeight: 800, color: 'var(--cp-text-primary)', lineHeight: 1.1, marginTop: 4, fontVariantNumeric: 'tabular-nums' },
  successKpiSub: { fontSize: 10, color: 'var(--cp-text-muted)', marginTop: 2 },

  successActions: { display: 'flex', gap: 10, flexWrap: 'wrap' },
  ctaPrimary: { padding: '10px 18px', borderRadius: 10, background: 'var(--cp-accent)', color: 'var(--cp-text-strong)', border: 'none', fontSize: 13, fontWeight: 700, cursor: 'pointer' },
  ctaSecondary: { padding: '10px 16px', borderRadius: 10, background: 'var(--cp-surface-0)', color: 'var(--cp-text-primary)', border: '1px solid var(--cp-border)', fontSize: 13, fontWeight: 600, cursor: 'pointer', textDecoration: 'none', display: 'inline-flex', alignItems: 'center' },
  successNote: { fontSize: 12, color: 'var(--cp-text-muted)', lineHeight: 1.5, paddingTop: 12, borderTop: '1px dashed var(--cp-border)', fontStyle: 'italic' },
};
